FROM node:22.15.0-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

COPY pnpm-lock.yaml package.json ./

RUN pnpm install

COPY . .

WORKDIR /app

EXPOSE 5173

CMD ["pnpm", "run", "dev"]
