# ========== Base Stage ===========
FROM node:22.16.0-slim AS base

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

# ========== Dev Stage ===========
FROM base AS dev

EXPOSE 5173
CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]
