FROM node:22.16.0-slim AS base

# Set working directory
WORKDIR /app

# Set environment variables
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Install pnpm globally
RUN npm install -g pnpm

# Copy package files
COPY pnpm-lock.yaml package.json ./

# Install dependencies using pnpm
RUN pnpm install --frozen-lockfile

# Copy the rest of the project files
COPY . .

# Expose port
EXPOSE 5173

# Start the app
CMD ["pnpm", "run", "dev"]
