services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./apps/api
    env_file: "./apps/api/.env.dev"
    volumes:
      - ./apps/api:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis

  bat_worker:
    build:
      dockerfile: cmd/email_worker/Dockerfile
      context: ./apps/api
      target: dev
    env_file: "./apps/api/.env.dev"
    volumes:
      - ./apps/api:/app
    working_dir: /app/cmd/BAT_worker
    depends_on:
      - redis

  email_worker:
    build:
      dockerfile: cmd/email_worker/Dockerfile
      context: ./apps/api
      target: dev
    env_file: "./apps/api/.env.dev"
    volumes:
      - ./apps/api:/app
    working_dir: /app/cmd/email_worker
    depends_on:
      - redis
  
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./apps/web:/app:cached
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  asynqmon:
    image: hibiken/asynqmon:latest
    platform: linux/amd64
    ports:
      - "6767:6767"
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=6767
    depends_on:
      - redis

  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coredb
    ports:
      - 5432:5432
    attach: false
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  loki:
    image: grafana/loki:3.7.1
    container_name: loki
    command: "-config.file=/etc/loki/config.yml"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/config.yml

  alloy:
    image: grafana/alloy:v1.15.0
    container_name: alloy
    command: run /etc/alloy/config.alloy
    volumes:
      - ./monitoring/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:12.4.2
    container_name: grafana
    env_file:
      - ./apps/api/.env
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Admin
      - GF_SERVER_ROOT_URL=http://localhost:8080/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./monitoring/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - alloy
      - api

  # web-devcontainer:
  #   build:
  #     context: ./.devcontainer/web
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/core
  #     - /core/apps/web/node_modules
  #   command: sleep infinity

  # api-devcontainer:
  #   build:
  #     context: ./.devcontainer/api
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/core
  #   command: sleep infinity

volumes:
  postgres_data:
  grafana_data:
