services:
  api:
    image: ghcr.io/swamphacks/core-api:latest
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - ./secrets/.env.api

  
  email-worker:
    image: ghcr.io/swamphacks/core-email-worker:latest
    restart: always
    env_file:
      - ./secrets/.env.api

