services:
  dev-api:
    image: ghcr.io/swamphacks/core-api:dev
    ports:
      - "8081:8080"
    restart: always
    env_file:
      - ./secrets/.env.dev.api

  dev-email-worker:
    image: ghcr.io/swamphacks/core-email-worker:dev
    restart: always
    env_file:
      - ./secrets/.env.dev.api
