FROM mcr.microsoft.com/devcontainers/go:2-1.25-trixie

RUN go install github.com/pressly/goose/v3/cmd/goose@latest
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
RUN go install go install github.com/hieunguyent12/swag/v2/cmd/swag@bcae90f384b937c1c47dbe9b5d8e7ba8cbe96aac