// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: event_roles.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO event_roles (event_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AssignRoleParams struct {
	EventID uuid.UUID     `json:"event_id"`
	UserID  uuid.UUID     `json:"user_id"`
	Role    EventRoleType `json:"role"`
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.EventID, arg.UserID, arg.Role)
	return err
}

const getEventAttendeesWithDiscord = `-- name: GetEventAttendeesWithDiscord :many
SELECT 
    a.account_id as discord_id,
    u.id as user_id,
    u.name,
    u.email
FROM auth.users u
JOIN event_roles er ON u.id = er.user_id
JOIN auth.accounts a ON u.id = a.user_id
WHERE er.event_id = $1
    AND er.role = 'attendee'
    AND a.provider_id = 'discord'
`

type GetEventAttendeesWithDiscordRow struct {
	DiscordID string    `json:"discord_id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	Email     *string   `json:"email"`
}

func (q *Queries) GetEventAttendeesWithDiscord(ctx context.Context, eventID uuid.UUID) ([]GetEventAttendeesWithDiscordRow, error) {
	rows, err := q.db.Query(ctx, getEventAttendeesWithDiscord, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventAttendeesWithDiscordRow{}
	for rows.Next() {
		var i GetEventAttendeesWithDiscordRow
		if err := rows.Scan(
			&i.DiscordID,
			&i.UserID,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventRoleByDiscordIDAndEventId = `-- name: GetEventRoleByDiscordIDAndEventId :one
SELECT er.event_id, er.role
FROM event_roles er
JOIN auth.accounts a ON er.user_id = a.user_id
WHERE a.provider_id = 'discord'
    AND a.account_id = $1
    AND er.event_id = $2
`

type GetEventRoleByDiscordIDAndEventIdParams struct {
	AccountID string    `json:"account_id"`
	EventID   uuid.UUID `json:"event_id"`
}

type GetEventRoleByDiscordIDAndEventIdRow struct {
	EventID uuid.UUID     `json:"event_id"`
	Role    EventRoleType `json:"role"`
}

func (q *Queries) GetEventRoleByDiscordIDAndEventId(ctx context.Context, arg GetEventRoleByDiscordIDAndEventIdParams) (GetEventRoleByDiscordIDAndEventIdRow, error) {
	row := q.db.QueryRow(ctx, getEventRoleByDiscordIDAndEventId, arg.AccountID, arg.EventID)
	var i GetEventRoleByDiscordIDAndEventIdRow
	err := row.Scan(&i.EventID, &i.Role)
	return i, err
}

const getEventStaff = `-- name: GetEventStaff :many
SELECT u.id, u.name, u.email, u.email_verified, u.onboarded, u.image, u.created_at, u.updated_at, u.role, u.preferred_email, u.email_consent, er.role AS event_role
FROM auth.users u
JOIN event_roles er ON u.id = er.user_id
WHERE er.event_id = $1
  AND er.role IN ('admin', 'staff')
`

type GetEventStaffRow struct {
	ID             uuid.UUID     `json:"id"`
	Name           string        `json:"name"`
	Email          *string       `json:"email"`
	EmailVerified  bool          `json:"email_verified"`
	Onboarded      bool          `json:"onboarded"`
	Image          *string       `json:"image"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	Role           AuthUserRole  `json:"role"`
	PreferredEmail *string       `json:"preferred_email"`
	EmailConsent   bool          `json:"email_consent"`
	EventRole      EventRoleType `json:"event_role"`
}

func (q *Queries) GetEventStaff(ctx context.Context, eventID uuid.UUID) ([]GetEventStaffRow, error) {
	rows, err := q.db.Query(ctx, getEventStaff, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventStaffRow{}
	for rows.Next() {
		var i GetEventStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Onboarded,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.PreferredEmail,
			&i.EmailConsent,
			&i.EventRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventUsers = `-- name: GetEventUsers :many
SELECT u.id, u.name, u.email, u.email_verified, u.onboarded, u.image, u.created_at, u.updated_at, u.role, u.preferred_email, u.email_consent, er.role AS event_role
FROM auth.users u
JOIN event_roles er ON u.id = er.user_id
WHERE er.event_id = $1
`

type GetEventUsersRow struct {
	ID             uuid.UUID     `json:"id"`
	Name           string        `json:"name"`
	Email          *string       `json:"email"`
	EmailVerified  bool          `json:"email_verified"`
	Onboarded      bool          `json:"onboarded"`
	Image          *string       `json:"image"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	Role           AuthUserRole  `json:"role"`
	PreferredEmail *string       `json:"preferred_email"`
	EmailConsent   bool          `json:"email_consent"`
	EventRole      EventRoleType `json:"event_role"`
}

func (q *Queries) GetEventUsers(ctx context.Context, eventID uuid.UUID) ([]GetEventUsersRow, error) {
	rows, err := q.db.Query(ctx, getEventUsers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEventUsersRow{}
	for rows.Next() {
		var i GetEventUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Onboarded,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.PreferredEmail,
			&i.EmailConsent,
			&i.EventRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRole = `-- name: RemoveRole :exec
DELETE FROM event_roles
WHERE event_id = $1
  AND user_id = $2
`

type RemoveRoleParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveRole(ctx context.Context, arg RemoveRoleParams) error {
	_, err := q.db.Exec(ctx, removeRole, arg.EventID, arg.UserID)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE event_roles
SET role = $3
WHERE event_id = $1 AND user_id = $2
`

type UpdateRoleParams struct {
	EventID uuid.UUID     `json:"event_id"`
	UserID  uuid.UUID     `json:"user_id"`
	Role    EventRoleType `json:"role"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.EventID, arg.UserID, arg.Role)
	return err
}
