// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    name,
    application_open, application_close,
    start_time, end_time,
    description, location, location_url, max_attendees,
    rsvp_deadline, decision_release, 
    website_url, is_published 
    -- saved_at is omitted due to having a default value (NOW) which will not be different if it was an optional param
) VALUES (
    -- FIXME: The second parameter in coalesce MUST be the default value created in the schema. I have not found a more automated way to insert the default value.
    $1,
    $2, $3,
    $4, $5,
    coalesce($6, NULL),
    coalesce($7, NULL),
    coalesce($8, NULL),
    coalesce($9, NULL::INT),     
    coalesce($10, NULL::TIMESTAMPTZ), 
    coalesce($11, NULL::TIMESTAMPTZ),
    coalesce($12, NULL),
    coalesce($13, FALSE)
) 
RETURNING id, name, description, location, location_url, max_attendees, application_open, application_close, rsvp_deadline, decision_release, start_time, end_time, website_url, is_published, saved_at, created_at, updated_at
`

type CreateEventParams struct {
	Name             string      `json:"name"`
	ApplicationOpen  time.Time   `json:"application_open"`
	ApplicationClose time.Time   `json:"application_close"`
	StartTime        time.Time   `json:"start_time"`
	EndTime          time.Time   `json:"end_time"`
	Description      interface{} `json:"description"`
	Location         interface{} `json:"location"`
	LocationUrl      interface{} `json:"location_url"`
	MaxAttendees     interface{} `json:"max_attendees"`
	RsvpDeadline     interface{} `json:"rsvp_deadline"`
	DecisionRelease  interface{} `json:"decision_release"`
	WebsiteUrl       interface{} `json:"website_url"`
	IsPublished      interface{} `json:"is_published"`
}

// TODO: allow optional parameters
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.ApplicationOpen,
		arg.ApplicationClose,
		arg.StartTime,
		arg.EndTime,
		arg.Description,
		arg.Location,
		arg.LocationUrl,
		arg.MaxAttendees,
		arg.RsvpDeadline,
		arg.DecisionRelease,
		arg.WebsiteUrl,
		arg.IsPublished,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.LocationUrl,
		&i.MaxAttendees,
		&i.ApplicationOpen,
		&i.ApplicationClose,
		&i.RsvpDeadline,
		&i.DecisionRelease,
		&i.StartTime,
		&i.EndTime,
		&i.WebsiteUrl,
		&i.IsPublished,
		&i.SavedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEventById = `-- name: DeleteEventById :execrows
DELETE FROM events
WHERE id = $1
`

// TODO: return error when 0 rows are deleted
func (q *Queries) DeleteEventById(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, name, description, location, location_url, max_attendees, application_open, application_close, rsvp_deadline, decision_release, start_time, end_time, website_url, is_published, saved_at, created_at, updated_at FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.LocationUrl,
		&i.MaxAttendees,
		&i.ApplicationOpen,
		&i.ApplicationClose,
		&i.RsvpDeadline,
		&i.DecisionRelease,
		&i.StartTime,
		&i.EndTime,
		&i.WebsiteUrl,
		&i.IsPublished,
		&i.SavedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEventById = `-- name: UpdateEventById :exec
UPDATE events
SET
    name = coalesce($1, name),
    description = coalesce($2, description),
    location = coalesce($3, location),
    location_url = coalesce($4, location_url),
    max_attendees = coalesce($5, max_attendees),
    application_open = coalesce($6, application_open),
    application_close = coalesce($7, application_close),
    rsvp_deadline = coalesce($8, rsvp_deadline),
    decision_release = coalesce($9, decision_release),
    start_time = coalesce($10, start_time),
    end_time = coalesce($11, end_time),
    website_url = coalesce($12, website_url),
    is_published = coalesce($13, is_published),
    saved_at = coalesce($14, is_published)
WHERE
    id = $15::uuid
`

type UpdateEventByIdParams struct {
	Name             *string    `json:"name"`
	Description      *string    `json:"description"`
	Location         *string    `json:"location"`
	LocationUrl      *string    `json:"location_url"`
	MaxAttendees     *int32     `json:"max_attendees"`
	ApplicationOpen  *time.Time `json:"application_open"`
	ApplicationClose *time.Time `json:"application_close"`
	RsvpDeadline     *time.Time `json:"rsvp_deadline"`
	DecisionRelease  *time.Time `json:"decision_release"`
	StartTime        *time.Time `json:"start_time"`
	EndTime          *time.Time `json:"end_time"`
	WebsiteUrl       *string    `json:"website_url"`
	IsPublished      *bool      `json:"is_published"`
	SavedAt          *time.Time `json:"saved_at"`
	ID               uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateEventById(ctx context.Context, arg UpdateEventByIdParams) error {
	_, err := q.db.Exec(ctx, updateEventById,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.LocationUrl,
		arg.MaxAttendees,
		arg.ApplicationOpen,
		arg.ApplicationClose,
		arg.RsvpDeadline,
		arg.DecisionRelease,
		arg.StartTime,
		arg.EndTime,
		arg.WebsiteUrl,
		arg.IsPublished,
		arg.SavedAt,
		arg.ID,
	)
	return err
}
