// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO auth.sessions (user_id, expires_at, ip_address, user_agent)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, expires_at, ip_address, user_agent, created_at, updated_at, last_used_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredSession = `-- name: DeleteExpiredSession :exec
DELETE FROM auth.sessions
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSession(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSession)
	return err
}

const getActiveSessionUserInfo = `-- name: GetActiveSessionUserInfo :one
SELECT u.id AS user_id, u.name, u.onboarded, u.image, u.role, s.last_used_at
FROM auth.sessions s
JOIN auth.users u ON s.user_id = u.id
WHERE s.id = $1
    AND (s.expires_at > NOW())
LIMIT 1
`

type GetActiveSessionUserInfoRow struct {
	UserID     uuid.UUID    `json:"user_id"`
	Name       string       `json:"name"`
	Onboarded  bool         `json:"onboarded"`
	Image      *string      `json:"image"`
	Role       AuthUserRole `json:"role"`
	LastUsedAt time.Time    `json:"last_used_at"`
}

func (q *Queries) GetActiveSessionUserInfo(ctx context.Context, id uuid.UUID) (GetActiveSessionUserInfoRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionUserInfo, id)
	var i GetActiveSessionUserInfoRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Onboarded,
		&i.Image,
		&i.Role,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, expires_at, ip_address, user_agent, created_at, updated_at, last_used_at FROM auth.sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT id, user_id, expires_at, ip_address, user_agent, created_at, updated_at, last_used_at FROM auth.sessions
WHERE user_id = $1
`

func (q *Queries) GetSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, getSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invalidateSessionByID = `-- name: InvalidateSessionByID :exec
UPDATE auth.sessions
SET expires_at = NOW()
WHERE id = $1
`

func (q *Queries) InvalidateSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateSessionByID, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE auth.sessions
SET expires_at = $2, last_used_at = NOW()
WHERE id = $1
`

type TouchSessionParams struct {
	ID        uuid.UUID `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}

const updateSessionExpiration = `-- name: UpdateSessionExpiration :exec
UPDATE auth.sessions
SET expires_at = $2
WHERE id = $1
`

type UpdateSessionExpirationParams struct {
	ID        uuid.UUID `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) UpdateSessionExpiration(ctx context.Context, arg UpdateSessionExpirationParams) error {
	_, err := q.db.Exec(ctx, updateSessionExpiration, arg.ID, arg.ExpiresAt)
	return err
}
