// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_members.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (
    user_id,
    team_id
) VALUES (
    $1,
    $2
)
RETURNING user_id, team_id, joined_at
`

type AddTeamMemberParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.UserID, arg.TeamID)
	var i TeamMember
	err := row.Scan(&i.UserID, &i.TeamID, &i.JoinedAt)
	return i, err
}

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO team_members (team_id, user_id)
VALUES ($1, $2)
RETURNING user_id, team_id, joined_at
`

type CreateTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, createTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(&i.UserID, &i.TeamID, &i.JoinedAt)
	return i, err
}

const getTeamMemberByUserAndEvent = `-- name: GetTeamMemberByUserAndEvent :one
SELECT tm.user_id, tm.team_id, tm.joined_at
FROM team_members tm
JOIN teams t on tm.team_id = t.id
WHERE tm.user_id = $1
    AND t.event_id = $2
LIMIT 1
`

type GetTeamMemberByUserAndEventParams struct {
	UserID  uuid.UUID  `json:"user_id"`
	EventID *uuid.UUID `json:"event_id"`
}

func (q *Queries) GetTeamMemberByUserAndEvent(ctx context.Context, arg GetTeamMemberByUserAndEventParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMemberByUserAndEvent, arg.UserID, arg.EventID)
	var i TeamMember
	err := row.Scan(&i.UserID, &i.TeamID, &i.JoinedAt)
	return i, err
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT
    u.id AS user_id,
    u.email,
    u.image,
    u.name,
    tm.joined_at
FROM
    team_members tm
JOIN
    auth.users u ON tm.user_id = u.id
WHERE
    tm.team_id = $1
`

type GetTeamMembersRow struct {
	UserID   uuid.UUID  `json:"user_id"`
	Email    *string    `json:"email"`
	Image    *string    `json:"image"`
	Name     string     `json:"name"`
	JoinedAt *time.Time `json:"joined_at"`
}

func (q *Queries) GetTeamMembers(ctx context.Context, teamID uuid.UUID) ([]GetTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, getTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTeamMembersRow{}
	for rows.Next() {
		var i GetTeamMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Image,
			&i.Name,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members
WHERE user_id = $1
  AND team_id = $2
`

type RemoveTeamMemberParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.UserID, arg.TeamID)
	return err
}
