// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: team_members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (
    user_id,
    team_id
) VALUES (
    $1,
    $2
)
RETURNING user_id, team_id, joined_at
`

type AddTeamMemberParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.UserID, arg.TeamID)
	var i TeamMember
	err := row.Scan(&i.UserID, &i.TeamID, &i.JoinedAt)
	return i, err
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members
WHERE user_id = $1
  AND team_id = $2
`

type RemoveTeamMemberParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.UserID, arg.TeamID)
	return err
}
