// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (name, email, image)
VALUES ($1, $2, $3)
RETURNING id, name, email, email_verified, onboarded, image, created_at, updated_at
`

type CreateUserParams struct {
	Name  string  `json:"name"`
	Email string  `json:"email"`
	Image *string `json:"image"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.Image)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Onboarded,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM auth.users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, email_verified, onboarded, image, created_at, updated_at FROM auth.users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Onboarded,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, email_verified, onboarded, image, created_at, updated_at FROM auth.users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Onboarded,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE auth.users
SET
    name = CASE WHEN $1::boolean THEN $2 ELSE name END,
    email = CASE WHEN $3::boolean THEN $4 ELSE email END,
    email_verified = CASE WHEN $5::boolean THEN $6 ELSE email_verified END,
    onboarded = CASE WHEN $7::boolean THEN $8 ELSE onboarded END,
    image = CASE WHEN $9::boolean THEN $10 ELSE image END,
    updated_at = NOW()
WHERE
    id = $11::uuid
`

type UpdateUserParams struct {
	NameDoUpdate          bool      `json:"name_do_update"`
	Name                  string    `json:"name"`
	EmailDoUpdate         bool      `json:"email_do_update"`
	Email                 string    `json:"email"`
	EmailVerifiedDoUpdate bool      `json:"email_verified_do_update"`
	EmailVerified         bool      `json:"email_verified"`
	OnboardedDoUpdate     bool      `json:"onboarded_do_update"`
	Onboarded             bool      `json:"onboarded"`
	ImageDoUpdate         bool      `json:"image_do_update"`
	Image                 *string   `json:"image"`
	ID                    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.NameDoUpdate,
		arg.Name,
		arg.EmailDoUpdate,
		arg.Email,
		arg.EmailVerifiedDoUpdate,
		arg.EmailVerified,
		arg.OnboardedDoUpdate,
		arg.Onboarded,
		arg.ImageDoUpdate,
		arg.Image,
		arg.ID,
	)
	return err
}

const updateUserOnboarded = `-- name: UpdateUserOnboarded :exec
UPDATE auth.users
SET onboarded = TRUE
WHERE id = $1
`

func (q *Queries) UpdateUserOnboarded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserOnboarded, id)
	return err
}
