openapi: 3.1.0
x-stoplight:
  id: zcud8lgb7c4sj
info:
  title: SwampHacks Core API
  version: '1.0'
  summary: 'The API powering SwampHacks, the University of Florida''s flagship hackathon.'
  description: 'The SwampHacks Core API provides the foundational backend services powering the SwampHacks ecosystem, enabling seamless event management, user authentication, data retrieval, and integrations for hackathon participants, organizers, and partners.'
  contact:
    name: Alexander wang
    url: ''
    email: alexanderwang@ufl.edu
  termsOfService: 'https://app.swamphacks.com/terms'
  license:
    name: Apache License 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: 'http://localhost:8080'
    description: Local Development
  - url: 'https://api.swamphacks.com'
    description: Production
  - url: 'https://dev.api.swamphacks.com'
    description: Staging
paths:
  /v1/auth/callback:
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    code: A008
                    error: invalid_oauth_params
                    message: The callbcak query parameters 'code' and/or 'state' was malformed or missing.
      operationId: post-v1-auth-callback
      x-stoplight:
        id: bzvqcbi7yjpv9
      description: This callback is for OAuth to retrieve the code and state in order to verify and log in a user.
      security: []
components:
  schemas:
    ErrorResponse:
      title: ErrorResponse
      x-stoplight:
        id: yqeintde5rzg2
      type: object
      description: An error response that returns error codes and messages for support and client side.
      x-internal: false
      examples:
        - code: A001
          error: token_invalid
          message: 'Your API token was invalid, plese try again.'
      properties:
        code:
          type: string
          x-stoplight:
            id: 1mrv1rrphcnip
        error:
          type: string
          x-stoplight:
            id: sjzi8o7w8wokk
        message:
          type: string
          x-stoplight:
            id: p096t705rbbb5
  securitySchemes:
    sh_session:
      type: http
      scheme: basic
      description: A session id token that persists a logged in state for users.
  responses: {}
security:
  - {}
  - sh_session: []
