services:
  web-devcontainer:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ..:/core
      - /core/apps/web/node_modules
    command: sleep infinity

  api-devcontainer:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ..:/core
    command: sleep infinity