// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: announcements.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (
    hackathon_id,
    title,
    body,
    source,
    updated_by_user_id,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4::announcement_source,
    $5::uuid,
    $6
)
RETURNING id, hackathon_id, title, body, source, created_at, updated_at, updated_by_user_id, expires_at
`

type CreateAnnouncementParams struct {
	HackathonID     string             `json:"hackathon_id"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	Source          AnnouncementSource `json:"source"`
	UpdatedByUserID *uuid.UUID         `json:"updated_by_user_id"`
	ExpiresAt       *time.Time         `json:"expires_at"`
}

// creates an announcement
func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.HackathonID,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.UpdatedByUserID,
		arg.ExpiresAt,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.HackathonID,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :exec
DELETE FROM announcements WHERE id = $1
`

// deletes an announcement
func (q *Queries) DeleteAnnouncement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnnouncement, id)
	return err
}

const dismissAnnouncement = `-- name: DismissAnnouncement :one
INSERT INTO users_dismissed_announcements (
    user_id,
    announcement_id
) VALUES (
    $1::uuid,
    $2::uuid
)
ON CONFLICT (user_id, announcement_id)
DO UPDATE SET
    dismissed_at = now()
RETURNING announcement_id
`

type DismissAnnouncementParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

// dismisses an announcement
func (q *Queries) DismissAnnouncement(ctx context.Context, arg DismissAnnouncementParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, dismissAnnouncement, arg.UserID, arg.ID)
	var announcement_id uuid.UUID
	err := row.Scan(&announcement_id)
	return announcement_id, err
}

const listActiveAnnouncements = `-- name: ListActiveAnnouncements :many
SELECT id, hackathon_id, title, body, source, created_at, updated_at, updated_by_user_id, expires_at
FROM announcements
WHERE hackathon_id = $1
    AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at DESC
`

// returns all active announcements for one hackathon
func (q *Queries) ListActiveAnnouncements(ctx context.Context, hackathonID string) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listActiveAnnouncements, hackathonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.HackathonID,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, hackathon_id, title, body, source, created_at, updated_at, updated_by_user_id, expires_at
FROM announcements
WHERE hackathon_id = $1
ORDER BY created_at DESC
`

// returns all announcements for one hackathon
func (q *Queries) ListAnnouncements(ctx context.Context, hackathonID string) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements, hackathonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.HackathonID,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDismissedAnnouncements = `-- name: ListDismissedAnnouncements :many
SELECT uda.announcement_id
FROM users_dismissed_announcements uda
JOIN announcements a
    ON a.id = uda.announcement_id
WHERE uda.user_id = $1
    AND (uda.dismissed_at >= a.updated_at)
`

// returns all dismissed announcements for a user
func (q *Queries) ListDismissedAnnouncements(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDismissedAnnouncements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var announcement_id uuid.UUID
		if err := rows.Scan(&announcement_id); err != nil {
			return nil, err
		}
		items = append(items, announcement_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcements
SET
    title =
        CASE WHEN $1::boolean
        THEN $2
        ELSE title END,
    body =
        CASE WHEN $3::boolean
        THEN $4
        ELSE body END,
    updated_by_user_id =
        CASE WHEN $5::boolean
        THEN $6::uuid
        ELSE updated_by_user_id END,
    expires_at =
        CASE WHEN $7::boolean
        THEN $8
        ELSE expires_at END
WHERE id = $9::uuid
    AND hackathon_id = $10
RETURNING id, hackathon_id, title, body, source, created_at, updated_at, updated_by_user_id, expires_at
`

type UpdateAnnouncementParams struct {
	TitleDoUpdate           bool       `json:"title_do_update"`
	Title                   string     `json:"title"`
	BodyDoUpdate            bool       `json:"body_do_update"`
	Body                    string     `json:"body"`
	UpdatedByUserIDDoUpdate bool       `json:"updated_by_user_id_do_update"`
	UpdatedByUserID         *uuid.UUID `json:"updated_by_user_id"`
	ExpiresAtDoUpdate       bool       `json:"expires_at_do_update"`
	ExpiresAt               *time.Time `json:"expires_at"`
	ID                      uuid.UUID  `json:"id"`
	HackathonID             string     `json:"hackathon_id"`
}

// edits an announcement
func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.TitleDoUpdate,
		arg.Title,
		arg.BodyDoUpdate,
		arg.Body,
		arg.UpdatedByUserIDDoUpdate,
		arg.UpdatedByUserID,
		arg.ExpiresAtDoUpdate,
		arg.ExpiresAt,
		arg.ID,
		arg.HackathonID,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.HackathonID,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserID,
		&i.ExpiresAt,
	)
	return i, err
}
