// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (
    name,
    description,
    role,
    expires_at,
    secret_hash
) VALUES (
    $1,
    $2,
    $3::role,
    $4,
    $5
)
RETURNING
    id,
    name,
    description,
    role,
    created_at,
    expires_at
`

type CreateApiKeyParams struct {
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Role        Role       `json:"role"`
	ExpiresAt   *time.Time `json:"expires_at"`
	SecretHash  string     `json:"secret_hash"`
}

type CreateApiKeyRow struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Role        Role       `json:"role"`
	CreatedAt   time.Time  `json:"created_at"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (CreateApiKeyRow, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.Name,
		arg.Description,
		arg.Role,
		arg.ExpiresAt,
		arg.SecretHash,
	)
	var i CreateApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM api_keys
WHERE id = $1
`

func (q *Queries) DeleteApiKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApiKey, id)
	return err
}

const getApiKeyById = `-- name: GetApiKeyById :one
SELECT
    id,
    name,
    description,
    role,
    created_at,
    expires_at
FROM api_keys
WHERE id = $1
`

type GetApiKeyByIdRow struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Role        Role       `json:"role"`
	CreatedAt   time.Time  `json:"created_at"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

func (q *Queries) GetApiKeyById(ctx context.Context, id uuid.UUID) (GetApiKeyByIdRow, error) {
	row := q.db.QueryRow(ctx, getApiKeyById, id)
	var i GetApiKeyByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getApiKeyBySecret = `-- name: GetApiKeyBySecret :one
SELECT
    id,
    expires_at
FROM api_keys
WHERE secret_hash = $1
    AND (expires_at IS NULL OR expires_at > NOW())
`

type GetApiKeyBySecretRow struct {
	ID        uuid.UUID  `json:"id"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) GetApiKeyBySecret(ctx context.Context, secretHash string) (GetApiKeyBySecretRow, error) {
	row := q.db.QueryRow(ctx, getApiKeyBySecret, secretHash)
	var i GetApiKeyBySecretRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT
    id,
    name,
    description,
    role,
    created_at,
    expires_at
FROM api_keys
ORDER BY created_at DESC
`

type ListApiKeysRow struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Role        Role       `json:"role"`
	CreatedAt   time.Time  `json:"created_at"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

func (q *Queries) ListApiKeys(ctx context.Context) ([]ListApiKeysRow, error) {
	rows, err := q.db.Query(ctx, listApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApiKeysRow{}
	for rows.Next() {
		var i ListApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Role,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
