// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: application_reviews.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignReviewerToApplications = `-- name: AssignReviewerToApplications :exec
INSERT INTO application_reviews (
    application_id,
    reviewer_id
)
SELECT applications.id, $1::uuid FROM applications
WHERE applications.id = ANY($2::uuid[])
ON CONFLICT DO NOTHING
`

type AssignReviewerToApplicationsParams struct {
	ReviewerID     uuid.UUID   `json:"reviewer_id"`
	ApplicationIds []uuid.UUID `json:"application_ids"`
}

func (q *Queries) AssignReviewerToApplications(ctx context.Context, arg AssignReviewerToApplicationsParams) error {
	_, err := q.db.Exec(ctx, assignReviewerToApplications, arg.ReviewerID, arg.ApplicationIds)
	return err
}

const deleteAllApplicationReviews = `-- name: DeleteAllApplicationReviews :exec
DELETE FROM application_reviews
`

func (q *Queries) DeleteAllApplicationReviews(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllApplicationReviews)
	return err
}

const deleteAllAutoDecisionRequests = `-- name: DeleteAllAutoDecisionRequests :exec
DELETE FROM application_auto_decision_requests
`

func (q *Queries) DeleteAllAutoDecisionRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllAutoDecisionRequests)
	return err
}

const deleteAutoDecisionRequest = `-- name: DeleteAutoDecisionRequest :exec
DELETE FROM application_auto_decision_requests
WHERE id = $1 AND reviewer_id = $2
`

type DeleteAutoDecisionRequestParams struct {
	ID         uuid.UUID `json:"id"`
	ReviewerID uuid.UUID `json:"reviewer_id"`
}

func (q *Queries) DeleteAutoDecisionRequest(ctx context.Context, arg DeleteAutoDecisionRequestParams) error {
	_, err := q.db.Exec(ctx, deleteAutoDecisionRequest, arg.ID, arg.ReviewerID)
	return err
}

const getAutoDecisionRequestsCount = `-- name: GetAutoDecisionRequestsCount :one
SELECT COUNT(*) FROM application_auto_decision_requests
`

func (q *Queries) GetAutoDecisionRequestsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAutoDecisionRequestsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReviewById = `-- name: GetReviewById :one
SELECT
    ar.id, ar.application_id, ar.reviewer_id, ar.experience_rating, ar.passion_rating, ar.notes, ar.updated_by, ar.created_at, ar.updated_at,
    aadr.requested_decision,
    aadr.id AS decision_request_id,
    aadr.justification AS decision_justification,
    aadr.approved AS decision_approved,
    aadr.decided_by AS decision_decided_by,
    aadr.created_at AS decision_request_created_at,
    applications.user_id,
    applications.application
FROM application_reviews AS ar
JOIN applications ON applications.id = ar.application_id
LEFT JOIN application_auto_decision_requests AS aadr ON aadr.application_id = ar.application_id
WHERE ar.id = $1
`

type GetReviewByIdRow struct {
	ID                       uuid.UUID                       `json:"id"`
	ApplicationID            uuid.UUID                       `json:"application_id"`
	ReviewerID               uuid.UUID                       `json:"reviewer_id"`
	ExperienceRating         *int32                          `json:"experience_rating"`
	PassionRating            *int32                          `json:"passion_rating"`
	Notes                    *string                         `json:"notes"`
	UpdatedBy                *uuid.UUID                      `json:"updated_by"`
	CreatedAt                time.Time                       `json:"created_at"`
	UpdatedAt                time.Time                       `json:"updated_at"`
	RequestedDecision        NullApplicationAutoDecisionType `json:"requested_decision"`
	DecisionRequestID        *uuid.UUID                      `json:"decision_request_id"`
	DecisionJustification    *string                         `json:"decision_justification"`
	DecisionApproved         *bool                           `json:"decision_approved"`
	DecisionDecidedBy        *uuid.UUID                      `json:"decision_decided_by"`
	DecisionRequestCreatedAt *time.Time                      `json:"decision_request_created_at"`
	UserID                   uuid.UUID                       `json:"user_id"`
	Application              []byte                          `json:"application"`
}

func (q *Queries) GetReviewById(ctx context.Context, reviewID uuid.UUID) (GetReviewByIdRow, error) {
	row := q.db.QueryRow(ctx, getReviewById, reviewID)
	var i GetReviewByIdRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ReviewerID,
		&i.ExperienceRating,
		&i.PassionRating,
		&i.Notes,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestedDecision,
		&i.DecisionRequestID,
		&i.DecisionJustification,
		&i.DecisionApproved,
		&i.DecisionDecidedBy,
		&i.DecisionRequestCreatedAt,
		&i.UserID,
		&i.Application,
	)
	return i, err
}

const listApplicationReviewersById = `-- name: ListApplicationReviewersById :many
SELECT reviewer_id FROM application_reviews
WHERE application_id = $1
`

func (q *Queries) ListApplicationReviewersById(ctx context.Context, applicationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listApplicationReviewersById, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var reviewer_id uuid.UUID
		if err := rows.Scan(&reviewer_id); err != nil {
			return nil, err
		}
		items = append(items, reviewer_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoDecisionRequests = `-- name: ListAutoDecisionRequests :many
SELECT
    aadr.id, aadr.application_id, aadr.reviewer_id, aadr.requested_decision, aadr.justification, aadr.approved, aadr.decided_by, aadr.updated_at, aadr.created_at,
    reviewer.name AS reviewer_name,
    reviewer.image AS reviewer_image,
    approver.id AS approver_id,
    approver.name AS approver_name,
    approver.image AS approver_image,
    applicant.id AS user_id,
    applicant.name AS user_name,
    applicant.image AS user_image
FROM application_auto_decision_requests AS aadr
JOIN users AS reviewer
    ON reviewer.id = aadr.reviewer_id
JOIN applications
    ON applications.id = aadr.application_id
JOIN users AS applicant
    ON applicant.id = applications.user_id
LEFT JOIN users AS approver
    ON approver.id = aadr.decided_by
ORDER BY aadr.created_at DESC
`

type ListAutoDecisionRequestsRow struct {
	ID                uuid.UUID                   `json:"id"`
	ApplicationID     uuid.UUID                   `json:"application_id"`
	ReviewerID        uuid.UUID                   `json:"reviewer_id"`
	RequestedDecision ApplicationAutoDecisionType `json:"requested_decision"`
	Justification     *string                     `json:"justification"`
	Approved          *bool                       `json:"approved"`
	DecidedBy         *uuid.UUID                  `json:"decided_by"`
	UpdatedAt         time.Time                   `json:"updated_at"`
	CreatedAt         time.Time                   `json:"created_at"`
	ReviewerName      string                      `json:"reviewer_name"`
	ReviewerImage     *string                     `json:"reviewer_image"`
	ApproverID        *uuid.UUID                  `json:"approver_id"`
	ApproverName      *string                     `json:"approver_name"`
	ApproverImage     *string                     `json:"approver_image"`
	UserID            uuid.UUID                   `json:"user_id"`
	UserName          string                      `json:"user_name"`
	UserImage         *string                     `json:"user_image"`
}

func (q *Queries) ListAutoDecisionRequests(ctx context.Context) ([]ListAutoDecisionRequestsRow, error) {
	rows, err := q.db.Query(ctx, listAutoDecisionRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAutoDecisionRequestsRow{}
	for rows.Next() {
		var i ListAutoDecisionRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ReviewerID,
			&i.RequestedDecision,
			&i.Justification,
			&i.Approved,
			&i.DecidedBy,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.ReviewerName,
			&i.ReviewerImage,
			&i.ApproverID,
			&i.ApproverName,
			&i.ApproverImage,
			&i.UserID,
			&i.UserName,
			&i.UserImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewersAndProgress = `-- name: ListReviewersAndProgress :many
SELECT
    reviewer.id,
    reviewer.name,
    reviewer.image,
    COUNT(*) AS total_assigned,
    COUNT(*) FILTER (
    WHERE ar.experience_rating IS NOT NULL AND ar.passion_rating IS NOT NULL
    ) AS completed_count
FROM application_reviews AS ar
LEFT JOIN users AS reviewer
  ON reviewer.id = ar.reviewer_id
GROUP BY
  reviewer.id
`

type ListReviewersAndProgressRow struct {
	ID             *uuid.UUID `json:"id"`
	Name           *string    `json:"name"`
	Image          *string    `json:"image"`
	TotalAssigned  int64      `json:"total_assigned"`
	CompletedCount int64      `json:"completed_count"`
}

func (q *Queries) ListReviewersAndProgress(ctx context.Context) ([]ListReviewersAndProgressRow, error) {
	rows, err := q.db.Query(ctx, listReviewersAndProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewersAndProgressRow{}
	for rows.Next() {
		var i ListReviewersAndProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.TotalAssigned,
			&i.CompletedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByReviewerId = `-- name: ListReviewsByReviewerId :many
SELECT 
    ar.id, ar.application_id, ar.reviewer_id, ar.experience_rating, ar.passion_rating, ar.notes, ar.updated_by, ar.created_at, ar.updated_at,
    applications.user_id
FROM application_reviews ar
JOIN applications ON applications.id = ar.application_id
WHERE reviewer_id = $1
ORDER BY application_id ASC
`

type ListReviewsByReviewerIdRow struct {
	ID               uuid.UUID  `json:"id"`
	ApplicationID    uuid.UUID  `json:"application_id"`
	ReviewerID       uuid.UUID  `json:"reviewer_id"`
	ExperienceRating *int32     `json:"experience_rating"`
	PassionRating    *int32     `json:"passion_rating"`
	Notes            *string    `json:"notes"`
	UpdatedBy        *uuid.UUID `json:"updated_by"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	UserID           uuid.UUID  `json:"user_id"`
}

func (q *Queries) ListReviewsByReviewerId(ctx context.Context, reviewerID uuid.UUID) ([]ListReviewsByReviewerIdRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByReviewerId, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByReviewerIdRow{}
	for rows.Next() {
		var i ListReviewsByReviewerIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ReviewerID,
			&i.ExperienceRating,
			&i.PassionRating,
			&i.Notes,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestAutoDecision = `-- name: RequestAutoDecision :one
INSERT INTO application_auto_decision_requests (application_id, reviewer_id, requested_decision, justification, approved, decided_by) 
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, application_id, reviewer_id, requested_decision, justification, approved, decided_by, updated_at, created_at
`

type RequestAutoDecisionParams struct {
	ApplicationID     uuid.UUID                   `json:"application_id"`
	ReviewerID        uuid.UUID                   `json:"reviewer_id"`
	RequestedDecision ApplicationAutoDecisionType `json:"requested_decision"`
	Justification     *string                     `json:"justification"`
	Approved          *bool                       `json:"approved"`
	DecidedBy         *uuid.UUID                  `json:"decided_by"`
}

func (q *Queries) RequestAutoDecision(ctx context.Context, arg RequestAutoDecisionParams) (ApplicationAutoDecisionRequest, error) {
	row := q.db.QueryRow(ctx, requestAutoDecision,
		arg.ApplicationID,
		arg.ReviewerID,
		arg.RequestedDecision,
		arg.Justification,
		arg.Approved,
		arg.DecidedBy,
	)
	var i ApplicationAutoDecisionRequest
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ReviewerID,
		&i.RequestedDecision,
		&i.Justification,
		&i.Approved,
		&i.DecidedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const searchAutoDecisionRequests = `-- name: SearchAutoDecisionRequests :many
SELECT
    aadr.id, aadr.application_id, aadr.reviewer_id, aadr.requested_decision, aadr.justification, aadr.approved, aadr.decided_by, aadr.updated_at, aadr.created_at,
    reviewer.name AS reviewer_name,
    reviewer.image AS reviewer_image,
    approver.id AS approver_id,
    approver.name AS approver_name,
    approver.image AS approver_image,
    applicant.id AS user_id,
    applicant.name AS user_name,
    applicant.image AS user_image
FROM application_auto_decision_requests AS aadr
JOIN users AS reviewer
    ON reviewer.id = aadr.reviewer_id
JOIN applications
    ON applications.id = aadr.application_id
JOIN users AS applicant
    ON applicant.id = applications.user_id
LEFT JOIN users AS approver
    ON approver.id = aadr.decided_by
WHERE (LOWER(reviewer.name) LIKE LOWER('%' || COALESCE($1, '') || '%')
    OR LOWER(applicant.name) LIKE LOWER('%' || COALESCE($1, '') || '%'))
    AND (
        $2::text = 'all'
        OR ($2::text = 'pending' AND aadr.approved IS NULL)
        OR ($2::text = 'approved' AND aadr.approved = true)
        OR ($2::text = 'denied' AND aadr.approved = false)
    )
    AND (
        $3::application_auto_decision_type IS NULL
        OR aadr.requested_decision = $3::application_auto_decision_type
    )
ORDER BY aadr.created_at DESC
LIMIT $5 OFFSET $4
`

type SearchAutoDecisionRequestsParams struct {
	Search   *string                         `json:"search"`
	Approved string                          `json:"approved"`
	Decision NullApplicationAutoDecisionType `json:"decision"`
	Offset   int32                           `json:"offset"`
	Limit    int32                           `json:"limit"`
}

type SearchAutoDecisionRequestsRow struct {
	ID                uuid.UUID                   `json:"id"`
	ApplicationID     uuid.UUID                   `json:"application_id"`
	ReviewerID        uuid.UUID                   `json:"reviewer_id"`
	RequestedDecision ApplicationAutoDecisionType `json:"requested_decision"`
	Justification     *string                     `json:"justification"`
	Approved          *bool                       `json:"approved"`
	DecidedBy         *uuid.UUID                  `json:"decided_by"`
	UpdatedAt         time.Time                   `json:"updated_at"`
	CreatedAt         time.Time                   `json:"created_at"`
	ReviewerName      string                      `json:"reviewer_name"`
	ReviewerImage     *string                     `json:"reviewer_image"`
	ApproverID        *uuid.UUID                  `json:"approver_id"`
	ApproverName      *string                     `json:"approver_name"`
	ApproverImage     *string                     `json:"approver_image"`
	UserID            uuid.UUID                   `json:"user_id"`
	UserName          string                      `json:"user_name"`
	UserImage         *string                     `json:"user_image"`
}

func (q *Queries) SearchAutoDecisionRequests(ctx context.Context, arg SearchAutoDecisionRequestsParams) ([]SearchAutoDecisionRequestsRow, error) {
	rows, err := q.db.Query(ctx, searchAutoDecisionRequests,
		arg.Search,
		arg.Approved,
		arg.Decision,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAutoDecisionRequestsRow{}
	for rows.Next() {
		var i SearchAutoDecisionRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ReviewerID,
			&i.RequestedDecision,
			&i.Justification,
			&i.Approved,
			&i.DecidedBy,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.ReviewerName,
			&i.ReviewerImage,
			&i.ApproverID,
			&i.ApproverName,
			&i.ApproverImage,
			&i.UserID,
			&i.UserName,
			&i.UserImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationReview = `-- name: UpdateApplicationReview :exec
UPDATE application_reviews
SET
    experience_rating = CASE WHEN $1::boolean THEN $2 ELSE experience_rating END,
    passion_rating = CASE WHEN $3::boolean THEN $4 ELSE passion_rating END,
    notes = CASE WHEN $5::boolean THEN $6 ELSE notes END,
    updated_by = CASE WHEN $7::boolean THEN $8 ELSE updated_by END,
    updated_at = NOW()
WHERE
    id = $9 AND
    reviewer_id = $10
`

type UpdateApplicationReviewParams struct {
	ExperienceRatingDoUpdate bool       `json:"experience_rating_do_update"`
	ExperienceRating         *int32     `json:"experience_rating"`
	PassionRatingDoUpdate    bool       `json:"passion_rating_do_update"`
	PassionRating            *int32     `json:"passion_rating"`
	NotesDoUpdate            bool       `json:"notes_do_update"`
	Notes                    *string    `json:"notes"`
	UpdatedByDoUpdate        bool       `json:"updated_by_do_update"`
	UpdatedBy                *uuid.UUID `json:"updated_by"`
	ID                       uuid.UUID  `json:"id"`
	ReviewerID               uuid.UUID  `json:"reviewer_id"`
}

func (q *Queries) UpdateApplicationReview(ctx context.Context, arg UpdateApplicationReviewParams) error {
	_, err := q.db.Exec(ctx, updateApplicationReview,
		arg.ExperienceRatingDoUpdate,
		arg.ExperienceRating,
		arg.PassionRatingDoUpdate,
		arg.PassionRating,
		arg.NotesDoUpdate,
		arg.Notes,
		arg.UpdatedByDoUpdate,
		arg.UpdatedBy,
		arg.ID,
		arg.ReviewerID,
	)
	return err
}

const updateAutoDecisionRequest = `-- name: UpdateAutoDecisionRequest :exec
UPDATE application_auto_decision_requests
SET
    requested_decision = CASE WHEN $1::boolean AND $2 <> '' THEN $2::application_auto_decision_type ELSE requested_decision END,
    justification = CASE WHEN $3::boolean THEN $4 ELSE justification END,
    approved = CASE WHEN $5::boolean THEN $6 ELSE approved END,
    decided_by = CASE WHEN $7::boolean THEN $8 ELSE decided_by END
WHERE id = $9 AND reviewer_id = $10
`

type UpdateAutoDecisionRequestParams struct {
	RequestedDecisionDoUpdate bool        `json:"requested_decision_do_update"`
	RequestedDecision         interface{} `json:"requested_decision"`
	JustificationDoUpdate     bool        `json:"justification_do_update"`
	Justification             *string     `json:"justification"`
	ApprovedDoUpdate          bool        `json:"approved_do_update"`
	Approved                  *bool       `json:"approved"`
	ApprovedByDoUpdate        bool        `json:"approved_by_do_update"`
	DecidedBy                 *uuid.UUID  `json:"decided_by"`
	ID                        uuid.UUID   `json:"id"`
	ReviewerID                uuid.UUID   `json:"reviewer_id"`
}

func (q *Queries) UpdateAutoDecisionRequest(ctx context.Context, arg UpdateAutoDecisionRequestParams) error {
	_, err := q.db.Exec(ctx, updateAutoDecisionRequest,
		arg.RequestedDecisionDoUpdate,
		arg.RequestedDecision,
		arg.JustificationDoUpdate,
		arg.Justification,
		arg.ApprovedDoUpdate,
		arg.Approved,
		arg.ApprovedByDoUpdate,
		arg.DecidedBy,
		arg.ID,
		arg.ReviewerID,
	)
	return err
}
