// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptWaitlistedApplications = `-- name: AcceptWaitlistedApplications :many
UPDATE applications
SET waitlist_join_time = NULL,
    status = 'accepted'
WHERE user_id IN (
  SELECT user_id FROM applications
  WHERE status = 'waitlisted'
  ORDER BY waitlist_join_time ASC
  LIMIT $1::int
)
RETURNING user_id
`

func (q *Queries) AcceptWaitlistedApplications(ctx context.Context, acceptancecount int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, acceptWaitlistedApplications, acceptancecount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (user_id, hackathon_id, is_early) VALUES ($1, $2, $3) RETURNING user_id, status, application, created_at, saved_at, updated_at, submitted_at, waitlist_join_time, hackathon_id, is_early
`

type CreateApplicationParams struct {
	UserID      uuid.UUID `json:"user_id"`
	HackathonID string    `json:"hackathon_id"`
	IsEarly     bool      `json:"is_early"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.UserID, arg.HackathonID, arg.IsEarly)
	var i Application
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Application,
		&i.CreatedAt,
		&i.SavedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.WaitlistJoinTime,
		&i.HackathonID,
		&i.IsEarly,
	)
	return i, err
}

const deleteApplicationByUserId = `-- name: DeleteApplicationByUserId :exec
DELETE FROM applications WHERE user_id = $1
`

func (q *Queries) DeleteApplicationByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplicationByUserId, userID)
	return err
}

const getApplicationByUserId = `-- name: GetApplicationByUserId :one
SELECT user_id, status, application, created_at, saved_at, updated_at, submitted_at, waitlist_join_time, hackathon_id, is_early FROM applications WHERE user_id = $1
`

func (q *Queries) GetApplicationByUserId(ctx context.Context, userID uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByUserId, userID)
	var i Application
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Application,
		&i.CreatedAt,
		&i.SavedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.WaitlistJoinTime,
		&i.HackathonID,
		&i.IsEarly,
	)
	return i, err
}

const listApplicationsUnderReviewWithTeamIds = `-- name: ListApplicationsUnderReviewWithTeamIds :many
SELECT a.user_id,
    a.application,
    t.id as team_id
FROM applications a
LEFT JOIN team_members tm
    ON tm.user_id = a.user_id
LEFT JOIN teams t
    ON t.id = tm.team_id
WHERE a.status = 'under_review'
`

type ListApplicationsUnderReviewWithTeamIdsRow struct {
	UserID      uuid.UUID  `json:"user_id"`
	Application []byte     `json:"application"`
	TeamID      *uuid.UUID `json:"team_id"`
}

func (q *Queries) ListApplicationsUnderReviewWithTeamIds(ctx context.Context) ([]ListApplicationsUnderReviewWithTeamIdsRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsUnderReviewWithTeamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsUnderReviewWithTeamIdsRow{}
	for rows.Next() {
		var i ListApplicationsUnderReviewWithTeamIdsRow
		if err := rows.Scan(&i.UserID, &i.Application, &i.TeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationByUserId = `-- name: UpdateApplicationByUserId :exec
UPDATE applications
SET
    status = CASE WHEN $1::boolean THEN $2::application_status ELSE status END,
    application = CASE WHEN $3::boolean THEN $4::JSONB ELSE application END,
    submitted_at = CASE WHEN $5::boolean THEN $6::timestamptz ELSE submitted_at END,
    saved_at = CASE WHEN $7::boolean THEN $8::timestamptz ELSE saved_at END,
    is_early = CASE WHEN $9::boolean THEN $10::boolean ELSE is_early END
WHERE
    user_id = $11
`

type UpdateApplicationByUserIdParams struct {
	StatusDoUpdate      bool              `json:"status_do_update"`
	Status              ApplicationStatus `json:"status"`
	ApplicationDoUpdate bool              `json:"application_do_update"`
	Application         []byte            `json:"application"`
	SubmittedAtDoUpdate bool              `json:"submitted_at_do_update"`
	SubmittedAt         time.Time         `json:"submitted_at"`
	SavedAtDoUpdate     bool              `json:"saved_at_do_update"`
	SavedAt             time.Time         `json:"saved_at"`
	IsEarlyDoUpdate     bool              `json:"is_early_do_update"`
	IsEarly             bool              `json:"is_early"`
	UserID              uuid.UUID         `json:"user_id"`
}

func (q *Queries) UpdateApplicationByUserId(ctx context.Context, arg UpdateApplicationByUserIdParams) error {
	_, err := q.db.Exec(ctx, updateApplicationByUserId,
		arg.StatusDoUpdate,
		arg.Status,
		arg.ApplicationDoUpdate,
		arg.Application,
		arg.SubmittedAtDoUpdate,
		arg.SubmittedAt,
		arg.SavedAtDoUpdate,
		arg.SavedAt,
		arg.IsEarlyDoUpdate,
		arg.IsEarly,
		arg.UserID,
	)
	return err
}

const updateApplicationsStatusByUserIds = `-- name: UpdateApplicationsStatusByUserIds :exec
UPDATE applications
SET status = $1::application_status
WHERE user_id = ANY($2::uuid[])
`

type UpdateApplicationsStatusByUserIdsParams struct {
	Status  ApplicationStatus `json:"status"`
	UserIds []uuid.UUID       `json:"user_ids"`
}

func (q *Queries) UpdateApplicationsStatusByUserIds(ctx context.Context, arg UpdateApplicationsStatusByUserIdsParams) error {
	_, err := q.db.Exec(ctx, updateApplicationsStatusByUserIds, arg.Status, arg.UserIds)
	return err
}

const waitlistAcceptedApplications = `-- name: WaitlistAcceptedApplications :exec
UPDATE applications
SET waitlist_join_time = COALESCE(waitlist_join_time, NOW()),
    status = 'waitlisted'
WHERE status = 'accepted'
  AND user_id IN (
    SELECT id from users
    WHERE role = 'applicant'
)
`

func (q *Queries) WaitlistAcceptedApplications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, waitlistAcceptedApplications)
	return err
}

const waitlistApplicationByUserId = `-- name: WaitlistApplicationByUserId :exec
UPDATE applications
SET waitlist_join_time = COALESCE(waitlist_join_time, NOW()),
    status = 'waitlisted'
WHERE user_id = $1
`

func (q *Queries) WaitlistApplicationByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, waitlistApplicationByUserId, userID)
	return err
}
