// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptWaitlistedApplications = `-- name: AcceptWaitlistedApplications :many
UPDATE applications
SET waitlist_join_time = NULL,
    status = 'accepted'
WHERE user_id IN (
  SELECT user_id FROM applications
  WHERE status = 'waitlisted'
  ORDER BY waitlist_join_time ASC
  LIMIT $1::int
)
RETURNING user_id
`

func (q *Queries) AcceptWaitlistedApplications(ctx context.Context, acceptancecount int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, acceptWaitlistedApplications, acceptancecount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (user_id, hackathon_id, is_early) VALUES ($1, $2, $3) RETURNING user_id, status, application, created_at, saved_at, updated_at, submitted_at, hackathon_id, is_early, id
`

type CreateApplicationParams struct {
	UserID      uuid.UUID `json:"user_id"`
	HackathonID string    `json:"hackathon_id"`
	IsEarly     bool      `json:"is_early"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.UserID, arg.HackathonID, arg.IsEarly)
	var i Application
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Application,
		&i.CreatedAt,
		&i.SavedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.HackathonID,
		&i.IsEarly,
		&i.ID,
	)
	return i, err
}

const deleteApplicationById = `-- name: DeleteApplicationById :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplicationById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplicationById, id)
	return err
}

const getApplicationById = `-- name: GetApplicationById :one
SELECT user_id, status, application, created_at, saved_at, updated_at, submitted_at, hackathon_id, is_early, id FROM applications WHERE id = $1
`

func (q *Queries) GetApplicationById(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationById, id)
	var i Application
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Application,
		&i.CreatedAt,
		&i.SavedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.HackathonID,
		&i.IsEarly,
		&i.ID,
	)
	return i, err
}

const getApplicationByUserId = `-- name: GetApplicationByUserId :one
SELECT user_id, status, application, created_at, saved_at, updated_at, submitted_at, hackathon_id, is_early, id FROM applications WHERE user_id = $1
`

func (q *Queries) GetApplicationByUserId(ctx context.Context, userID uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByUserId, userID)
	var i Application
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Application,
		&i.CreatedAt,
		&i.SavedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.HackathonID,
		&i.IsEarly,
		&i.ID,
	)
	return i, err
}

const getApplicationsCount = `-- name: GetApplicationsCount :one
SELECT COUNT(*) FROM applications WHERE hackathon_id = $1
`

func (q *Queries) GetApplicationsCount(ctx context.Context, hackathonID string) (int64, error) {
	row := q.db.QueryRow(ctx, getApplicationsCount, hackathonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExtendedApplicationById = `-- name: GetExtendedApplicationById :one
SELECT 
    a.user_id, a.status, a.application, a.created_at, a.saved_at, a.updated_at, a.submitted_at, a.hackathon_id, a.is_early, a.id,
    ar.id AS review_id,
    ar.experience_rating, 
    ar.passion_rating, 
    ar.notes, 
    ar.updated_at AS review_updated_at,
    ar.updated_by AS review_updated_by,
    reviewer.id AS reviewer_id,
    reviewer.name AS reviewer_name, 
    reviewer.image AS reviewer_image,
    applicant.name AS user_name,
    applicant.image AS user_image,
    aadr.requested_decision,
    aadr.id AS auto_decision_request_id,
    aadr.justification AS decision_justification,
    aadr.approved AS decision_approved,
    aadr.approved_or_denied_by,
    aadr.created_at AS decision_request_created_at
FROM applications a
JOIN users AS applicant ON applicant.id = a.user_id
LEFT JOIN application_reviews AS ar ON ar.application_id = a.id
LEFT JOIN users AS reviewer ON reviewer.id = ar.reviewer_id
LEFT JOIN application_auto_decision_requests as aadr ON aadr.application_id = a.id
WHERE a.id = $1
`

type GetExtendedApplicationByIdRow struct {
	UserID                   uuid.UUID                       `json:"user_id"`
	Status                   ApplicationStatus               `json:"status"`
	Application              []byte                          `json:"application"`
	CreatedAt                time.Time                       `json:"created_at"`
	SavedAt                  time.Time                       `json:"saved_at"`
	UpdatedAt                time.Time                       `json:"updated_at"`
	SubmittedAt              *time.Time                      `json:"submitted_at"`
	HackathonID              string                          `json:"hackathon_id"`
	IsEarly                  bool                            `json:"is_early"`
	ID                       uuid.UUID                       `json:"id"`
	ReviewID                 *uuid.UUID                      `json:"review_id"`
	ExperienceRating         *int32                          `json:"experience_rating"`
	PassionRating            *int32                          `json:"passion_rating"`
	Notes                    *string                         `json:"notes"`
	ReviewUpdatedAt          *time.Time                      `json:"review_updated_at"`
	ReviewUpdatedBy          *uuid.UUID                      `json:"review_updated_by"`
	ReviewerID               *uuid.UUID                      `json:"reviewer_id"`
	ReviewerName             *string                         `json:"reviewer_name"`
	ReviewerImage            *string                         `json:"reviewer_image"`
	UserName                 string                          `json:"user_name"`
	UserImage                *string                         `json:"user_image"`
	RequestedDecision        NullApplicationAutoDecisionType `json:"requested_decision"`
	AutoDecisionRequestID    *uuid.UUID                      `json:"auto_decision_request_id"`
	DecisionJustification    *string                         `json:"decision_justification"`
	DecisionApproved         *bool                           `json:"decision_approved"`
	ApprovedOrDeniedBy       *uuid.UUID                      `json:"approved_or_denied_by"`
	DecisionRequestCreatedAt *time.Time                      `json:"decision_request_created_at"`
}

func (q *Queries) GetExtendedApplicationById(ctx context.Context, id uuid.UUID) (GetExtendedApplicationByIdRow, error) {
	row := q.db.QueryRow(ctx, getExtendedApplicationById, id)
	var i GetExtendedApplicationByIdRow
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Application,
		&i.CreatedAt,
		&i.SavedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.HackathonID,
		&i.IsEarly,
		&i.ID,
		&i.ReviewID,
		&i.ExperienceRating,
		&i.PassionRating,
		&i.Notes,
		&i.ReviewUpdatedAt,
		&i.ReviewUpdatedBy,
		&i.ReviewerID,
		&i.ReviewerName,
		&i.ReviewerImage,
		&i.UserName,
		&i.UserImage,
		&i.RequestedDecision,
		&i.AutoDecisionRequestID,
		&i.DecisionJustification,
		&i.DecisionApproved,
		&i.ApprovedOrDeniedBy,
		&i.DecisionRequestCreatedAt,
	)
	return i, err
}

const listApplicationsUnderReviewWithTeamIds = `-- name: ListApplicationsUnderReviewWithTeamIds :many
SELECT 
    a.user_id,
    a.application,
    t.id as team_id
FROM applications a
LEFT JOIN team_members tm
    ON tm.user_id = a.user_id
LEFT JOIN teams t
    ON t.id = tm.team_id
WHERE a.status = 'under_review'
`

type ListApplicationsUnderReviewWithTeamIdsRow struct {
	UserID      uuid.UUID  `json:"user_id"`
	Application []byte     `json:"application"`
	TeamID      *uuid.UUID `json:"team_id"`
}

func (q *Queries) ListApplicationsUnderReviewWithTeamIds(ctx context.Context) ([]ListApplicationsUnderReviewWithTeamIdsRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsUnderReviewWithTeamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsUnderReviewWithTeamIdsRow{}
	for rows.Next() {
		var i ListApplicationsUnderReviewWithTeamIdsRow
		if err := rows.Scan(&i.UserID, &i.Application, &i.TeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnderReviewApplicationIds = `-- name: ListUnderReviewApplicationIds :many
SELECT id FROM applications
WHERE status = 'under_review' AND hackathon_id = $1
ORDER BY id ASC
`

func (q *Queries) ListUnderReviewApplicationIds(ctx context.Context, hackathonID string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUnderReviewApplicationIds, hackathonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubmittedApplicationsAsUnderReview = `-- name: MarkSubmittedApplicationsAsUnderReview :exec
UPDATE applications 
SET status = 'under_review'
WHERE status = 'submitted'
`

func (q *Queries) MarkSubmittedApplicationsAsUnderReview(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markSubmittedApplicationsAsUnderReview)
	return err
}

const resetApplicationsToSubmitted = `-- name: ResetApplicationsToSubmitted :exec
UPDATE applications 
SET status = 'submitted'
WHERE status = 'under_review'
`

func (q *Queries) ResetApplicationsToSubmitted(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetApplicationsToSubmitted)
	return err
}

const searchApplicationsWithUserInfo = `-- name: SearchApplicationsWithUserInfo :many
SELECT 
    a.id, 
    a.user_id, 
    a.status, 
    a.created_at, 
    a.submitted_at, 
    a.application, 
    a.is_early, 
    u.name, 
    u.image, 
    u.email 
FROM applications a
JOIN users u ON u.id = a.user_id
WHERE (LOWER(u.name) LIKE LOWER('%' || COALESCE($1, '') || '%')
    OR LOWER(u.email) LIKE LOWER('%' || COALESCE($1, '') || '%'))
    AND a.hackathon_id = $2
ORDER BY a.created_at DESC
LIMIT $4 OFFSET $3
`

type SearchApplicationsWithUserInfoParams struct {
	Search      *string `json:"search"`
	HackathonID string  `json:"hackathon_id"`
	Offset      int32   `json:"offset"`
	Limit       int32   `json:"limit"`
}

type SearchApplicationsWithUserInfoRow struct {
	ID          uuid.UUID         `json:"id"`
	UserID      uuid.UUID         `json:"user_id"`
	Status      ApplicationStatus `json:"status"`
	CreatedAt   time.Time         `json:"created_at"`
	SubmittedAt *time.Time        `json:"submitted_at"`
	Application []byte            `json:"application"`
	IsEarly     bool              `json:"is_early"`
	Name        string            `json:"name"`
	Image       *string           `json:"image"`
	Email       *string           `json:"email"`
}

func (q *Queries) SearchApplicationsWithUserInfo(ctx context.Context, arg SearchApplicationsWithUserInfoParams) ([]SearchApplicationsWithUserInfoRow, error) {
	rows, err := q.db.Query(ctx, searchApplicationsWithUserInfo,
		arg.Search,
		arg.HackathonID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchApplicationsWithUserInfoRow{}
	for rows.Next() {
		var i SearchApplicationsWithUserInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.Application,
			&i.IsEarly,
			&i.Name,
			&i.Image,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationById = `-- name: UpdateApplicationById :exec
UPDATE applications
SET
    status = CASE WHEN $1::boolean THEN $2::application_status ELSE status END,
    application = CASE WHEN $3::boolean THEN $4::JSONB ELSE application END,
    submitted_at = CASE WHEN $5::boolean THEN $6::timestamptz ELSE submitted_at END,
    saved_at = CASE WHEN $7::boolean THEN $8::timestamptz ELSE saved_at END,
    is_early = CASE WHEN $9::boolean THEN $10::boolean ELSE is_early END
WHERE
    id = $11
`

type UpdateApplicationByIdParams struct {
	StatusDoUpdate      bool              `json:"status_do_update"`
	Status              ApplicationStatus `json:"status"`
	ApplicationDoUpdate bool              `json:"application_do_update"`
	Application         []byte            `json:"application"`
	SubmittedAtDoUpdate bool              `json:"submitted_at_do_update"`
	SubmittedAt         time.Time         `json:"submitted_at"`
	SavedAtDoUpdate     bool              `json:"saved_at_do_update"`
	SavedAt             time.Time         `json:"saved_at"`
	IsEarlyDoUpdate     bool              `json:"is_early_do_update"`
	IsEarly             bool              `json:"is_early"`
	ID                  uuid.UUID         `json:"id"`
}

func (q *Queries) UpdateApplicationById(ctx context.Context, arg UpdateApplicationByIdParams) error {
	_, err := q.db.Exec(ctx, updateApplicationById,
		arg.StatusDoUpdate,
		arg.Status,
		arg.ApplicationDoUpdate,
		arg.Application,
		arg.SubmittedAtDoUpdate,
		arg.SubmittedAt,
		arg.SavedAtDoUpdate,
		arg.SavedAt,
		arg.IsEarlyDoUpdate,
		arg.IsEarly,
		arg.ID,
	)
	return err
}

const updateApplicationByUserId = `-- name: UpdateApplicationByUserId :exec
UPDATE applications
SET
    status = CASE WHEN $1::boolean THEN $2::application_status ELSE status END,
    application = CASE WHEN $3::boolean THEN $4::JSONB ELSE application END,
    submitted_at = CASE WHEN $5::boolean THEN $6::timestamptz ELSE submitted_at END,
    saved_at = CASE WHEN $7::boolean THEN $8::timestamptz ELSE saved_at END,
    is_early = CASE WHEN $9::boolean THEN $10::boolean ELSE is_early END
WHERE
    user_id = $11
`

type UpdateApplicationByUserIdParams struct {
	StatusDoUpdate      bool              `json:"status_do_update"`
	Status              ApplicationStatus `json:"status"`
	ApplicationDoUpdate bool              `json:"application_do_update"`
	Application         []byte            `json:"application"`
	SubmittedAtDoUpdate bool              `json:"submitted_at_do_update"`
	SubmittedAt         time.Time         `json:"submitted_at"`
	SavedAtDoUpdate     bool              `json:"saved_at_do_update"`
	SavedAt             time.Time         `json:"saved_at"`
	IsEarlyDoUpdate     bool              `json:"is_early_do_update"`
	IsEarly             bool              `json:"is_early"`
	UserID              uuid.UUID         `json:"user_id"`
}

func (q *Queries) UpdateApplicationByUserId(ctx context.Context, arg UpdateApplicationByUserIdParams) error {
	_, err := q.db.Exec(ctx, updateApplicationByUserId,
		arg.StatusDoUpdate,
		arg.Status,
		arg.ApplicationDoUpdate,
		arg.Application,
		arg.SubmittedAtDoUpdate,
		arg.SubmittedAt,
		arg.SavedAtDoUpdate,
		arg.SavedAt,
		arg.IsEarlyDoUpdate,
		arg.IsEarly,
		arg.UserID,
	)
	return err
}

const updateApplicationsStatusByIds = `-- name: UpdateApplicationsStatusByIds :exec
UPDATE applications
SET status = $1::application_status
WHERE id = ANY($2::uuid[])
`

type UpdateApplicationsStatusByIdsParams struct {
	Status ApplicationStatus `json:"status"`
	Ids    []uuid.UUID       `json:"ids"`
}

func (q *Queries) UpdateApplicationsStatusByIds(ctx context.Context, arg UpdateApplicationsStatusByIdsParams) error {
	_, err := q.db.Exec(ctx, updateApplicationsStatusByIds, arg.Status, arg.Ids)
	return err
}

const waitlistAcceptedApplications = `-- name: WaitlistAcceptedApplications :exec
UPDATE applications
SET waitlist_join_time = COALESCE(waitlist_join_time, NOW()),
    status = 'waitlisted'
WHERE status = 'accepted'
  AND user_id IN (
    SELECT id from users
    WHERE role = 'applicant'
)
`

func (q *Queries) WaitlistAcceptedApplications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, waitlistAcceptedApplications)
	return err
}

const waitlistApplicationById = `-- name: WaitlistApplicationById :exec
UPDATE applications
SET waitlist_join_time = COALESCE(waitlist_join_time, NOW()),
    status = 'waitlisted'
WHERE id = $1
`

func (q *Queries) WaitlistApplicationById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, waitlistApplicationById, id)
	return err
}
