// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: application_reviews.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignReviewerToApplications = `-- name: AssignReviewerToApplications :exec
INSERT INTO application_reviews (
    application_id,
    reviewer_user_id
)
SELECT applications.user_id, $1::uuid
FROM applications
WHERE applications.user_id = ANY($2::uuid[])
ON CONFLICT DO NOTHING
`

type AssignReviewerToApplicationsParams struct {
	ReviewerID     uuid.UUID   `json:"reviewer_id"`
	ApplicationIds []uuid.UUID `json:"application_ids"`
}

func (q *Queries) AssignReviewerToApplications(ctx context.Context, arg AssignReviewerToApplicationsParams) error {
	_, err := q.db.Exec(ctx, assignReviewerToApplications, arg.ReviewerID, arg.ApplicationIds)
	return err
}

const deleteAllApplicationReviews = `-- name: DeleteAllApplicationReviews :exec
DELETE FROM application_reviews
`

func (q *Queries) DeleteAllApplicationReviews(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllApplicationReviews)
	return err
}

const deleteAllAutoDecisionRequests = `-- name: DeleteAllAutoDecisionRequests :exec
DELETE FROM application_auto_decision_requests
`

func (q *Queries) DeleteAllAutoDecisionRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllAutoDecisionRequests)
	return err
}

const deleteAutoDecisionRequest = `-- name: DeleteAutoDecisionRequest :exec
DELETE FROM application_auto_decision_requests 
WHERE id = $1::uuid AND reviewer_user_id = $2::uuid
`

type DeleteAutoDecisionRequestParams struct {
	RequestID  uuid.UUID `json:"request_id"`
	ReviewerID uuid.UUID `json:"reviewer_id"`
}

func (q *Queries) DeleteAutoDecisionRequest(ctx context.Context, arg DeleteAutoDecisionRequestParams) error {
	_, err := q.db.Exec(ctx, deleteAutoDecisionRequest, arg.RequestID, arg.ReviewerID)
	return err
}

const getApplicationReviewDetails = `-- name: GetApplicationReviewDetails :one
SELECT ar.application_id, ar.passion_rating, ar.experience_rating, ar.notes, a.application, aadr.requested_decision, aadr.id as auto_decision_request_id FROM application_reviews as ar
LEFT JOIN applications as a ON ar.application_id = a.user_id
LEFT JOIN application_auto_decision_requests as aadr ON ar.application_id = aadr.application_id
WHERE ar.application_id = $1::uuid
`

type GetApplicationReviewDetailsRow struct {
	ApplicationID         uuid.UUID                       `json:"application_id"`
	PassionRating         *int32                          `json:"passion_rating"`
	ExperienceRating      *int32                          `json:"experience_rating"`
	Notes                 *string                         `json:"notes"`
	Application           []byte                          `json:"application"`
	RequestedDecision     NullApplicationAutoDecisionType `json:"requested_decision"`
	AutoDecisionRequestID *uuid.UUID                      `json:"auto_decision_request_id"`
}

func (q *Queries) GetApplicationReviewDetails(ctx context.Context, applicationID uuid.UUID) (GetApplicationReviewDetailsRow, error) {
	row := q.db.QueryRow(ctx, getApplicationReviewDetails, applicationID)
	var i GetApplicationReviewDetailsRow
	err := row.Scan(
		&i.ApplicationID,
		&i.PassionRating,
		&i.ExperienceRating,
		&i.Notes,
		&i.Application,
		&i.RequestedDecision,
		&i.AutoDecisionRequestID,
	)
	return i, err
}

const listAutoDecisionRequests = `-- name: ListAutoDecisionRequests :many
SELECT
  aadr.id, aadr.application_id, aadr.reviewer_user_id, aadr.requested_decision, aadr.justification, aadr.approved, aadr.approved_or_denied_by, aadr.updated_at, aadr.created_at,
  reviewer.id AS reviewer_id,
  reviewer.name AS reviewer_name,
  reviewer.image AS reviewer_image,
  approver.id AS approver_id,
  approver.name AS approver_name
FROM application_auto_decision_requests AS aadr
LEFT JOIN users AS reviewer
  ON reviewer.id = aadr.reviewer_user_id
LEFT JOIN users AS approver
  ON approver.id = aadr.approved_or_denied_by
ORDER BY aadr.created_at
`

type ListAutoDecisionRequestsRow struct {
	ID                 uuid.UUID                   `json:"id"`
	ApplicationID      uuid.UUID                   `json:"application_id"`
	ReviewerUserID     *uuid.UUID                  `json:"reviewer_user_id"`
	RequestedDecision  ApplicationAutoDecisionType `json:"requested_decision"`
	Justification      *string                     `json:"justification"`
	Approved           *bool                       `json:"approved"`
	ApprovedOrDeniedBy *uuid.UUID                  `json:"approved_or_denied_by"`
	UpdatedAt          time.Time                   `json:"updated_at"`
	CreatedAt          time.Time                   `json:"created_at"`
	ReviewerID         *uuid.UUID                  `json:"reviewer_id"`
	ReviewerName       *string                     `json:"reviewer_name"`
	ReviewerImage      *string                     `json:"reviewer_image"`
	ApproverID         *uuid.UUID                  `json:"approver_id"`
	ApproverName       *string                     `json:"approver_name"`
}

func (q *Queries) ListAutoDecisionRequests(ctx context.Context) ([]ListAutoDecisionRequestsRow, error) {
	rows, err := q.db.Query(ctx, listAutoDecisionRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAutoDecisionRequestsRow{}
	for rows.Next() {
		var i ListAutoDecisionRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.ReviewerUserID,
			&i.RequestedDecision,
			&i.Justification,
			&i.Approved,
			&i.ApprovedOrDeniedBy,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.ReviewerID,
			&i.ReviewerName,
			&i.ReviewerImage,
			&i.ApproverID,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewersAndProgress = `-- name: ListReviewersAndProgress :many
SELECT
  reviewer.id,
  reviewer.name,
  reviewer.image,
  COUNT(*) AS total_assigned,
  COUNT(*) FILTER (
    WHERE ar.experience_rating IS NOT NULL AND ar.passion_rating IS NOT NULL
  ) AS completed_count
FROM application_reviews AS ar
LEFT JOIN users AS reviewer
  ON reviewer.id = ar.reviewer_user_id
GROUP BY
  reviewer.id
`

type ListReviewersAndProgressRow struct {
	ID             *uuid.UUID `json:"id"`
	Name           *string    `json:"name"`
	Image          *string    `json:"image"`
	TotalAssigned  int64      `json:"total_assigned"`
	CompletedCount int64      `json:"completed_count"`
}

func (q *Queries) ListReviewersAndProgress(ctx context.Context) ([]ListReviewersAndProgressRow, error) {
	rows, err := q.db.Query(ctx, listReviewersAndProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewersAndProgressRow{}
	for rows.Next() {
		var i ListReviewersAndProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.TotalAssigned,
			&i.CompletedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewersByApplicationId = `-- name: ListReviewersByApplicationId :many
SELECT reviewer_user_id FROM application_reviews
WHERE application_id = $1::uuid
`

func (q *Queries) ListReviewersByApplicationId(ctx context.Context, applicationID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listReviewersByApplicationId, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var reviewer_user_id uuid.UUID
		if err := rows.Scan(&reviewer_user_id); err != nil {
			return nil, err
		}
		items = append(items, reviewer_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByReviewerId = `-- name: ListReviewsByReviewerId :many
SELECT application_id, experience_rating, passion_rating FROM application_reviews
WHERE reviewer_user_id = $1::uuid
ORDER BY application_id ASC
`

type ListReviewsByReviewerIdRow struct {
	ApplicationID    uuid.UUID `json:"application_id"`
	ExperienceRating *int32    `json:"experience_rating"`
	PassionRating    *int32    `json:"passion_rating"`
}

func (q *Queries) ListReviewsByReviewerId(ctx context.Context, reviewerID uuid.UUID) ([]ListReviewsByReviewerIdRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByReviewerId, reviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByReviewerIdRow{}
	for rows.Next() {
		var i ListReviewsByReviewerIdRow
		if err := rows.Scan(&i.ApplicationID, &i.ExperienceRating, &i.PassionRating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnderReviewApplicationIds = `-- name: ListUnderReviewApplicationIds :many
SELECT user_id FROM applications
WHERE status = 'under_review'
ORDER BY user_id ASC
`

func (q *Queries) ListUnderReviewApplicationIds(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUnderReviewApplicationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubmittedApplicationAsUnderReview = `-- name: MarkSubmittedApplicationAsUnderReview :exec
UPDATE applications 
SET status = 'under_review'
WHERE status = 'submitted'
`

func (q *Queries) MarkSubmittedApplicationAsUnderReview(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markSubmittedApplicationAsUnderReview)
	return err
}

const requestAutoDecision = `-- name: RequestAutoDecision :exec
INSERT INTO application_auto_decision_requests 
(application_id, reviewer_user_id, requested_decision, justification, approved, approved_or_denied_by) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, application_id, reviewer_user_id, requested_decision, justification, approved, approved_or_denied_by, updated_at, created_at
`

type RequestAutoDecisionParams struct {
	ApplicationID      uuid.UUID                   `json:"application_id"`
	ReviewerUserID     *uuid.UUID                  `json:"reviewer_user_id"`
	RequestedDecision  ApplicationAutoDecisionType `json:"requested_decision"`
	Justification      *string                     `json:"justification"`
	Approved           *bool                       `json:"approved"`
	ApprovedOrDeniedBy *uuid.UUID                  `json:"approved_or_denied_by"`
}

func (q *Queries) RequestAutoDecision(ctx context.Context, arg RequestAutoDecisionParams) error {
	_, err := q.db.Exec(ctx, requestAutoDecision,
		arg.ApplicationID,
		arg.ReviewerUserID,
		arg.RequestedDecision,
		arg.Justification,
		arg.Approved,
		arg.ApprovedOrDeniedBy,
	)
	return err
}

const resetApplicationsToSubmitted = `-- name: ResetApplicationsToSubmitted :exec
UPDATE applications 
SET status = 'submitted'
WHERE status = 'under_review'
`

func (q *Queries) ResetApplicationsToSubmitted(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetApplicationsToSubmitted)
	return err
}

const updateApplicationReview = `-- name: UpdateApplicationReview :exec
UPDATE application_reviews
SET
    experience_rating = CASE WHEN $1::boolean THEN $2 ELSE experience_rating END,
    passion_rating = CASE WHEN $3::boolean THEN $4 ELSE passion_rating END,
    notes = CASE WHEN $5::boolean THEN $6 ELSE notes END,
    updated_at = NOW()
WHERE
    reviewer_user_id = $7::uuid AND 
    application_id = $8::uuid
`

type UpdateApplicationReviewParams struct {
	ExperienceRatingDoUpdate bool      `json:"experience_rating_do_update"`
	ExperienceRating         *int32    `json:"experience_rating"`
	PassionRatingDoUpdate    bool      `json:"passion_rating_do_update"`
	PassionRating            *int32    `json:"passion_rating"`
	NotesDoUpdate            bool      `json:"notes_do_update"`
	Notes                    *string   `json:"notes"`
	ReviewerID               uuid.UUID `json:"reviewer_id"`
	ApplicationID            uuid.UUID `json:"application_id"`
}

func (q *Queries) UpdateApplicationReview(ctx context.Context, arg UpdateApplicationReviewParams) error {
	_, err := q.db.Exec(ctx, updateApplicationReview,
		arg.ExperienceRatingDoUpdate,
		arg.ExperienceRating,
		arg.PassionRatingDoUpdate,
		arg.PassionRating,
		arg.NotesDoUpdate,
		arg.Notes,
		arg.ReviewerID,
		arg.ApplicationID,
	)
	return err
}

const updateAutoDecisionRequest = `-- name: UpdateAutoDecisionRequest :exec
UPDATE application_auto_decision_requests
SET
    requested_decision = CASE WHEN $1::boolean AND $2 <> '' THEN $2::application_auto_decision_type ELSE requested_decision END,
    justification = CASE WHEN $3::boolean THEN $4 ELSE justification END,
    approved = CASE WHEN $5::boolean THEN $6 ELSE approved END,
    approved_or_denied_by = CASE WHEN $7::boolean THEN $8 ELSE approved_or_denied_by END
WHERE
    id = $9::uuid
`

type UpdateAutoDecisionRequestParams struct {
	RequestedDecisionDoUpdate bool        `json:"requested_decision_do_update"`
	RequestedDecision         interface{} `json:"requested_decision"`
	JustificationDoUpdate     bool        `json:"justification_do_update"`
	Justification             *string     `json:"justification"`
	ApprovedDoUpdate          bool        `json:"approved_do_update"`
	Approved                  *bool       `json:"approved"`
	ApprovedByDoUpdate        bool        `json:"approved_by_do_update"`
	ApprovedOrDeniedBy        *uuid.UUID  `json:"approved_or_denied_by"`
	RequestID                 uuid.UUID   `json:"request_id"`
}

func (q *Queries) UpdateAutoDecisionRequest(ctx context.Context, arg UpdateAutoDecisionRequestParams) error {
	_, err := q.db.Exec(ctx, updateAutoDecisionRequest,
		arg.RequestedDecisionDoUpdate,
		arg.RequestedDecision,
		arg.JustificationDoUpdate,
		arg.Justification,
		arg.ApprovedDoUpdate,
		arg.Approved,
		arg.ApprovedByDoUpdate,
		arg.ApprovedOrDeniedBy,
		arg.RequestID,
	)
	return err
}
