// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nfc.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const checkinUser = `-- name: checkinUser :one
INSERT INTO nfc_tags_user (tag_id, user_id) VALUES
($1, $2)
ON CONFLICT DO NOTHING 
RETURNING id, tag_id, user_id, created_at, updated_at
`

type checkinUserParams struct {
	TagID  string     `json:"tag_id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) checkinUser(ctx context.Context, arg checkinUserParams) (NfcTagsUser, error) {
	row := q.db.QueryRow(ctx, checkinUser, arg.TagID, arg.UserID)
	var i NfcTagsUser
	err := row.Scan(
		&i.ID,
		&i.TagID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeals = `-- name: getMeals :many
SELECT name, id, max_user_amount FROM redeemables
WHERE type = 'meal'
Order by name
`

type getMealsRow struct {
	Name          string    `json:"name"`
	ID            uuid.UUID `json:"id"`
	MaxUserAmount int32     `json:"max_user_amount"`
}

func (q *Queries) getMeals(ctx context.Context) ([]getMealsRow, error) {
	rows, err := q.db.Query(ctx, getMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []getMealsRow{}
	for rows.Next() {
		var i getMealsRow
		if err := rows.Scan(&i.Name, &i.ID, &i.MaxUserAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSocials = `-- name: getSocials :many
SELECT title as name, id FROM workshops
WHERE type = 'social'
ORDER BY title
`

type getSocialsRow struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) getSocials(ctx context.Context) ([]getSocialsRow, error) {
	rows, err := q.db.Query(ctx, getSocials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []getSocialsRow{}
	for rows.Next() {
		var i getSocialsRow
		if err := rows.Scan(&i.Name, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTshirts = `-- name: getTshirts :many
SELECT name, id, max_user_amount FROM redeemables
where type = 'tshirt'
Order by name
`

type getTshirtsRow struct {
	Name          string    `json:"name"`
	ID            uuid.UUID `json:"id"`
	MaxUserAmount int32     `json:"max_user_amount"`
}

func (q *Queries) getTshirts(ctx context.Context) ([]getTshirtsRow, error) {
	rows, err := q.db.Query(ctx, getTshirts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []getTshirtsRow{}
	for rows.Next() {
		var i getTshirtsRow
		if err := rows.Scan(&i.Name, &i.ID, &i.MaxUserAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkshops = `-- name: getWorkshops :many
SELECT title as name, id FROM workshops
WHERE type = 'workshop'
ORDER BY title
`

type getWorkshopsRow struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) getWorkshops(ctx context.Context) ([]getWorkshopsRow, error) {
	rows, err := q.db.Query(ctx, getWorkshops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []getWorkshopsRow{}
	for rows.Next() {
		var i getWorkshopsRow
		if err := rows.Scan(&i.Name, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagToRedeemable = `-- name: tagToRedeemable :exec
INSERT INTO nfc_tags_redeemables (tag_id, redeemable_id) VALUES ($1, $2)
`

type tagToRedeemableParams struct {
	TagID        string    `json:"tag_id"`
	RedeemableID uuid.UUID `json:"redeemable_id"`
}

func (q *Queries) tagToRedeemable(ctx context.Context, arg tagToRedeemableParams) error {
	_, err := q.db.Exec(ctx, tagToRedeemable, arg.TagID, arg.RedeemableID)
	return err
}

const tagToWorkshop = `-- name: tagToWorkshop :execrows
INSERT INTO nfc_tags_workshops (tag_id, workshop_id)
VALUES ($1, $2)
ON CONFLICT (tag_id, workshop_id) DO NOTHING
`

type tagToWorkshopParams struct {
	TagID      string    `json:"tag_id"`
	WorkshopID uuid.UUID `json:"workshop_id"`
}

func (q *Queries) tagToWorkshop(ctx context.Context, arg tagToWorkshopParams) (int64, error) {
	result, err := q.db.Exec(ctx, tagToWorkshop, arg.TagID, arg.WorkshopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
