// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nfc.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const checkinUser = `-- name: CheckinUser :one
INSERT INTO nfc_tags_user (tag_id, user_id) VALUES
($1, $2)
ON CONFLICT DO NOTHING 
RETURNING id, tag_id, user_id, created_at, updated_at
`

type CheckinUserParams struct {
	TagID  string     `json:"tag_id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckinUser(ctx context.Context, arg CheckinUserParams) (NfcTagsUser, error) {
	row := q.db.QueryRow(ctx, checkinUser, arg.TagID, arg.UserID)
	var i NfcTagsUser
	err := row.Scan(
		&i.ID,
		&i.TagID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeals = `-- name: GetMeals :many
SELECT name, id, max_user_amount FROM redeemables
WHERE type = 'meal'
Order by name
`

type GetMealsRow struct {
	Name          string    `json:"name"`
	ID            uuid.UUID `json:"id"`
	MaxUserAmount int32     `json:"max_user_amount"`
}

func (q *Queries) GetMeals(ctx context.Context) ([]GetMealsRow, error) {
	rows, err := q.db.Query(ctx, getMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMealsRow{}
	for rows.Next() {
		var i GetMealsRow
		if err := rows.Scan(&i.Name, &i.ID, &i.MaxUserAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSocials = `-- name: GetSocials :many
SELECT title as name, id FROM workshops
WHERE type = 'social'
ORDER BY title
`

type GetSocialsRow struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) GetSocials(ctx context.Context) ([]GetSocialsRow, error) {
	rows, err := q.db.Query(ctx, getSocials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSocialsRow{}
	for rows.Next() {
		var i GetSocialsRow
		if err := rows.Scan(&i.Name, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTshirts = `-- name: GetTshirts :many
SELECT name, id, max_user_amount FROM redeemables
where type = 'tshirt'
Order by name
`

type GetTshirtsRow struct {
	Name          string    `json:"name"`
	ID            uuid.UUID `json:"id"`
	MaxUserAmount int32     `json:"max_user_amount"`
}

func (q *Queries) GetTshirts(ctx context.Context) ([]GetTshirtsRow, error) {
	rows, err := q.db.Query(ctx, getTshirts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTshirtsRow{}
	for rows.Next() {
		var i GetTshirtsRow
		if err := rows.Scan(&i.Name, &i.ID, &i.MaxUserAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkshops = `-- name: GetWorkshops :many
SELECT title as name, id FROM workshops
WHERE type = 'workshop'
ORDER BY title
`

type GetWorkshopsRow struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) GetWorkshops(ctx context.Context) ([]GetWorkshopsRow, error) {
	rows, err := q.db.Query(ctx, getWorkshops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkshopsRow{}
	for rows.Next() {
		var i GetWorkshopsRow
		if err := rows.Scan(&i.Name, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagToRedeemable = `-- name: TagToRedeemable :exec
INSERT INTO nfc_tags_redeemables (tag_id, redeemable_id) VALUES ($1, $2)
`

type TagToRedeemableParams struct {
	TagID        string    `json:"tag_id"`
	RedeemableID uuid.UUID `json:"redeemable_id"`
}

func (q *Queries) TagToRedeemable(ctx context.Context, arg TagToRedeemableParams) error {
	_, err := q.db.Exec(ctx, tagToRedeemable, arg.TagID, arg.RedeemableID)
	return err
}

const tagToWorkshop = `-- name: TagToWorkshop :execrows
INSERT INTO nfc_tags_workshops (tag_id, workshop_id)
VALUES ($1, $2)
ON CONFLICT (tag_id, workshop_id) DO NOTHING
`

type TagToWorkshopParams struct {
	TagID      string    `json:"tag_id"`
	WorkshopID uuid.UUID `json:"workshop_id"`
}

func (q *Queries) TagToWorkshop(ctx context.Context, arg TagToWorkshopParams) (int64, error) {
	result, err := q.db.Exec(ctx, tagToWorkshop, arg.TagID, arg.WorkshopID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
