// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workshops.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWorkshop = `-- name: CreateWorkshop :one
INSERT INTO workshops (title, description, start_time, end_time, location, presenter)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, start_time, end_time, curr_attendees, location, presenter, created_at, updated_at
`

type CreateWorkshopParams struct {
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	Location    *string   `json:"location"`
	Presenter   *string   `json:"presenter"`
}

func (q *Queries) CreateWorkshop(ctx context.Context, arg CreateWorkshopParams) (Workshop, error) {
	row := q.db.QueryRow(ctx, createWorkshop,
		arg.Title,
		arg.Description,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.Presenter,
	)
	var i Workshop
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CurrAttendees,
		&i.Location,
		&i.Presenter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementWorkshopAttendees = `-- name: DecrementWorkshopAttendees :exec
UPDATE workshops
SET curr_attendees = GREATEST(curr_attendees - 1, 0)
WHERE id = $1
`

func (q *Queries) DecrementWorkshopAttendees(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementWorkshopAttendees, id)
	return err
}

const deleteWorkshop = `-- name: DeleteWorkshop :exec
DELETE FROM workshops
WHERE id = $1
`

func (q *Queries) DeleteWorkshop(ctx context.Context, workshopID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkshop, workshopID)
	return err
}

const getAllWorkshops = `-- name: GetAllWorkshops :many
SELECT w.id, w.title, w.description, w.start_time, w.end_time, w.curr_attendees, w.location, w.presenter, w.created_at, w.updated_at FROM workshops w
WHERE w.start_time > CURRENT_TIMESTAMP
ORDER BY w.start_time ASC
`

func (q *Queries) GetAllWorkshops(ctx context.Context) ([]Workshop, error) {
	rows, err := q.db.Query(ctx, getAllWorkshops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workshop{}
	for rows.Next() {
		var i Workshop
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartTime,
			&i.EndTime,
			&i.CurrAttendees,
			&i.Location,
			&i.Presenter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkshop = `-- name: GetWorkshop :one
SELECT w.id, w.title, w.description, w.start_time, w.end_time, w.curr_attendees, w.location, w.presenter, w.created_at, w.updated_at FROM workshops w
WHERE w.id = $1
`

func (q *Queries) GetWorkshop(ctx context.Context, workshopID uuid.UUID) (Workshop, error) {
	row := q.db.QueryRow(ctx, getWorkshop, workshopID)
	var i Workshop
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartTime,
		&i.EndTime,
		&i.CurrAttendees,
		&i.Location,
		&i.Presenter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkshopRegistrations = `-- name: GetWorkshopRegistrations :many
SELECT user_id, workshop_id, created_at
FROM workshop_registrations
WHERE workshop_id = $1
`

func (q *Queries) GetWorkshopRegistrations(ctx context.Context, workshopID uuid.UUID) ([]WorkshopRegistration, error) {
	rows, err := q.db.Query(ctx, getWorkshopRegistrations, workshopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkshopRegistration{}
	for rows.Next() {
		var i WorkshopRegistration
		if err := rows.Scan(&i.UserID, &i.WorkshopID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementWorkshopAttendees = `-- name: IncrementWorkshopAttendees :exec
UPDATE workshops
SET curr_attendees = curr_attendees + 1
WHERE id = $1
`

func (q *Queries) IncrementWorkshopAttendees(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementWorkshopAttendees, id)
	return err
}

const isUserRegistered = `-- name: IsUserRegistered :one
SELECT EXISTS (
    SELECT 1
    FROM workshop_registrations
    WHERE user_id = $1 AND workshop_id = $2
)
`

type IsUserRegisteredParams struct {
	UserID     uuid.UUID `json:"user_id"`
	WorkshopID uuid.UUID `json:"workshop_id"`
}

func (q *Queries) IsUserRegistered(ctx context.Context, arg IsUserRegisteredParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserRegistered, arg.UserID, arg.WorkshopID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const registerUserForWorkshop = `-- name: RegisterUserForWorkshop :exec
INSERT INTO workshop_registrations (user_id, workshop_id)
VALUES ($1, $2)
`

type RegisterUserForWorkshopParams struct {
	UserID     uuid.UUID `json:"user_id"`
	WorkshopID uuid.UUID `json:"workshop_id"`
}

func (q *Queries) RegisterUserForWorkshop(ctx context.Context, arg RegisterUserForWorkshopParams) error {
	_, err := q.db.Exec(ctx, registerUserForWorkshop, arg.UserID, arg.WorkshopID)
	return err
}

const unregisterUserForWorkshop = `-- name: UnregisterUserForWorkshop :exec
DELETE FROM workshop_registrations
WHERE user_id = $1 AND workshop_id = $2
`

type UnregisterUserForWorkshopParams struct {
	UserID     uuid.UUID `json:"user_id"`
	WorkshopID uuid.UUID `json:"workshop_id"`
}

func (q *Queries) UnregisterUserForWorkshop(ctx context.Context, arg UnregisterUserForWorkshopParams) error {
	_, err := q.db.Exec(ctx, unregisterUserForWorkshop, arg.UserID, arg.WorkshopID)
	return err
}
