# FROM python:3.12-slim

# RUN pip install uv

# WORKDIR /app

# COPY pyproject.toml .
# COPY uv.lock .

# # ENV PATH="/root/.local/bin:$PATH"

# RUN uv sync --frozen --no-cache --all-extras

# COPY . .

# EXPOSE 3000

# CMD ["uv", "run", "main.py"]
# # CMD ["uv", "run", "api_server.py"]
