// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bat_runs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addBatRun = `-- name: AddBatRun :one
INSERT INTO bat_runs DEFAULT VALUES RETURNING id, accepted_applicants, rejected_applicants, status, created_at, completed_at, hackathon_id
`

func (q *Queries) AddBatRun(ctx context.Context) (BatRun, error) {
	row := q.db.QueryRow(ctx, addBatRun)
	var i BatRun
	err := row.Scan(
		&i.ID,
		&i.AcceptedApplicants,
		&i.RejectedApplicants,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.HackathonID,
	)
	return i, err
}

const deleteBatRunById = `-- name: DeleteBatRunById :execrows
DELETE FROM bat_runs
WHERE id = $1
`

func (q *Queries) DeleteBatRunById(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBatRunById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBatRunById = `-- name: GetBatRunById :one
SELECT id, accepted_applicants, rejected_applicants, status, created_at, completed_at, hackathon_id
FROM bat_runs
WHERE id = $1
`

func (q *Queries) GetBatRunById(ctx context.Context, id uuid.UUID) (BatRun, error) {
	row := q.db.QueryRow(ctx, getBatRunById, id)
	var i BatRun
	err := row.Scan(
		&i.ID,
		&i.AcceptedApplicants,
		&i.RejectedApplicants,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.HackathonID,
	)
	return i, err
}

const getBatRuns = `-- name: GetBatRuns :many
SELECT
    id, accepted_applicants, rejected_applicants, status, created_at, completed_at, hackathon_id
FROM bat_runs
ORDER BY created_at DESC
`

func (q *Queries) GetBatRuns(ctx context.Context) ([]BatRun, error) {
	rows, err := q.db.Query(ctx, getBatRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatRun{}
	for rows.Next() {
		var i BatRun
		if err := rows.Scan(
			&i.ID,
			&i.AcceptedApplicants,
			&i.RejectedApplicants,
			&i.Status,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.HackathonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatRunById = `-- name: UpdateBatRunById :exec
UPDATE bat_runs
SET
    accepted_applicants = CASE WHEN $1::boolean THEN $2 ELSE accepted_applicants END,
    rejected_applicants = CASE WHEN $3::boolean THEN $4 ELSE rejected_applicants END,
    status = CASE WHEN $5::boolean THEN $6 ELSE status END,
    created_at = CASE WHEN $7::boolean THEN $8 ELSE created_at END
WHERE
    id = $9::uuid
RETURNING id, accepted_applicants, rejected_applicants, status, created_at, completed_at, hackathon_id
`

type UpdateBatRunByIdParams struct {
	AcceptedApplicantsDoUpdate bool         `json:"accepted_applicants_do_update"`
	AcceptedApplicants         []uuid.UUID  `json:"accepted_applicants"`
	RejectedApplicantsDoUpdate bool         `json:"rejected_applicants_do_update"`
	RejectedApplicants         []uuid.UUID  `json:"rejected_applicants"`
	StatusDoUpdate             bool         `json:"status_do_update"`
	Status                     BatRunStatus `json:"status"`
	CreatedAtDoUpdate          bool         `json:"created_at_do_update"`
	CreatedAt                  time.Time    `json:"created_at"`
	ID                         uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateBatRunById(ctx context.Context, arg UpdateBatRunByIdParams) error {
	_, err := q.db.Exec(ctx, updateBatRunById,
		arg.AcceptedApplicantsDoUpdate,
		arg.AcceptedApplicants,
		arg.RejectedApplicantsDoUpdate,
		arg.RejectedApplicants,
		arg.StatusDoUpdate,
		arg.Status,
		arg.CreatedAtDoUpdate,
		arg.CreatedAt,
		arg.ID,
	)
	return err
}
