// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_roles.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO event_roles (user_id, role)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleParams struct {
	UserID uuid.UUID     `json:"user_id"`
	Role   EventRoleType `json:"role"`
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.Role)
	return err
}

const getRoleByDiscordID = `-- name: GetRoleByDiscordID :one
SELECT er.role
FROM event_roles er
JOIN auth.accounts a ON er.user_id = a.user_id
WHERE a.provider_id = 'discord'
    AND a.account_id = $1
`

func (q *Queries) GetRoleByDiscordID(ctx context.Context, accountID string) (EventRoleType, error) {
	row := q.db.QueryRow(ctx, getRoleByDiscordID, accountID)
	var role EventRoleType
	err := row.Scan(&role)
	return role, err
}

const removeRole = `-- name: RemoveRole :exec
DELETE FROM event_roles
WHERE user_id = $1
`

func (q *Queries) RemoveRole(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeRole, userID)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE event_roles
SET role = $2
WHERE user_id = $1
`

type UpdateRoleParams struct {
	UserID uuid.UUID     `json:"user_id"`
	Role   EventRoleType `json:"role"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.UserID, arg.Role)
	return err
}

const updateRoleByUserId = `-- name: UpdateRoleByUserId :exec
UPDATE event_roles
SET
  role = CASE WHEN $1::boolean THEN $2 ELSE role END,
  rfid = CASE WHEN $3::boolean THEN $4 ELSE rfid END,
  checked_in_at = CASE WHEN $5::boolean THEN $6 ELSE checked_in_at END
WHERE user_id = $7
`

type UpdateRoleByUserIdParams struct {
	RoleDoUpdate        bool          `json:"role_do_update"`
	Role                EventRoleType `json:"role"`
	RfidDoUpdate        bool          `json:"rfid_do_update"`
	Rfid                *string       `json:"rfid"`
	CheckedInAtDoUpdate bool          `json:"checked_in_at_do_update"`
	CheckedInAt         *time.Time    `json:"checked_in_at"`
	UserID              uuid.UUID     `json:"user_id"`
}

func (q *Queries) UpdateRoleByUserId(ctx context.Context, arg UpdateRoleByUserIdParams) error {
	_, err := q.db.Exec(ctx, updateRoleByUserId,
		arg.RoleDoUpdate,
		arg.Role,
		arg.RfidDoUpdate,
		arg.Rfid,
		arg.CheckedInAtDoUpdate,
		arg.CheckedInAt,
		arg.UserID,
	)
	return err
}
