// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_roles.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO event_roles (user_id, role)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleParams struct {
	UserID uuid.UUID     `json:"user_id"`
	Role   EventRoleType `json:"role"`
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.Role)
	return err
}

const getAttendeeCount = `-- name: GetAttendeeCount :one
SELECT COUNT(*) FROM event_roles AS er
WHERE er.role = 'attendee'
`

func (q *Queries) GetAttendeeCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAttendeeCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAttendeeUserIds = `-- name: GetAttendeeUserIds :many
SELECT er.user_id FROM event_roles AS er
WHERE er.role = 'attendee'
`

func (q *Queries) GetAttendeeUserIds(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAttendeeUserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendeesWithDiscord = `-- name: GetAttendeesWithDiscord :many
SELECT 
    a.account_id as discord_id,
    u.id as user_id,
    u.name,
    u.email
FROM auth.users u
JOIN event_roles er ON u.id = er.user_id
JOIN auth.accounts a ON u.id = a.user_id
WHERE er.role = 'attendee'
    AND a.provider_id = 'discord'
`

type GetAttendeesWithDiscordRow struct {
	DiscordID string    `json:"discord_id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	Email     *string   `json:"email"`
}

func (q *Queries) GetAttendeesWithDiscord(ctx context.Context) ([]GetAttendeesWithDiscordRow, error) {
	rows, err := q.db.Query(ctx, getAttendeesWithDiscord)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttendeesWithDiscordRow{}
	for rows.Next() {
		var i GetAttendeesWithDiscordRow
		if err := rows.Scan(
			&i.DiscordID,
			&i.UserID,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckedInStatusByUserIds = `-- name: GetCheckedInStatusByUserIds :one
SELECT EXISTS (
    SELECT 1 
    FROM event_roles 
    WHERE user_id = $1 
      AND checked_in_at IS NOT NULL
)::bool
`

func (q *Queries) GetCheckedInStatusByUserIds(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getCheckedInStatusByUserIds, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getRoleByDiscordID = `-- name: GetRoleByDiscordID :one
SELECT er.role
FROM event_roles er
JOIN auth.accounts a ON er.user_id = a.user_id
WHERE a.provider_id = 'discord'
    AND a.account_id = $1
`

func (q *Queries) GetRoleByDiscordID(ctx context.Context, accountID string) (EventRoleType, error) {
	row := q.db.QueryRow(ctx, getRoleByDiscordID, accountID)
	var role EventRoleType
	err := row.Scan(&role)
	return role, err
}

const getStaff = `-- name: GetStaff :many
SELECT u.id, u.name, u.email, u.email_verified, u.onboarded, u.image, u.created_at, u.updated_at, u.role, u.preferred_email, u.email_consent, er.role AS event_role
FROM auth.users u
JOIN event_roles er ON u.id = er.user_id
WHERE er.role IN ('admin', 'staff')
`

type GetStaffRow struct {
	ID             uuid.UUID     `json:"id"`
	Name           string        `json:"name"`
	Email          *string       `json:"email"`
	EmailVerified  bool          `json:"email_verified"`
	Onboarded      bool          `json:"onboarded"`
	Image          *string       `json:"image"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	Role           AuthUserRole  `json:"role"`
	PreferredEmail *string       `json:"preferred_email"`
	EmailConsent   bool          `json:"email_consent"`
	EventRole      EventRoleType `json:"event_role"`
}

func (q *Queries) GetStaff(ctx context.Context) ([]GetStaffRow, error) {
	rows, err := q.db.Query(ctx, getStaff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaffRow{}
	for rows.Next() {
		var i GetStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Onboarded,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.PreferredEmail,
			&i.EmailConsent,
			&i.EventRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByRFID = `-- name: GetUserByRFID :one
SELECT u.id, u.name, u.email, u.email_verified, u.onboarded, u.image, u.created_at, u.updated_at, u.role, u.preferred_email, u.email_consent
FROM auth.users u
JOIN event_roles er ON u.id = er.user_id
WHERE er.rfid = $1
`

func (q *Queries) GetUserByRFID(ctx context.Context, rfid *string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByRFID, rfid)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Onboarded,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.PreferredEmail,
		&i.EmailConsent,
	)
	return i, err
}

const getUsesWithRoles = `-- name: GetUsesWithRoles :many
SELECT u.id, u.name, u.email, u.email_verified, u.onboarded, u.image, u.created_at, u.updated_at, u.role, u.preferred_email, u.email_consent, er.role AS event_role
FROM auth.users u
JOIN event_roles er ON u.id = er.user_id
`

type GetUsesWithRolesRow struct {
	ID             uuid.UUID     `json:"id"`
	Name           string        `json:"name"`
	Email          *string       `json:"email"`
	EmailVerified  bool          `json:"email_verified"`
	Onboarded      bool          `json:"onboarded"`
	Image          *string       `json:"image"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	Role           AuthUserRole  `json:"role"`
	PreferredEmail *string       `json:"preferred_email"`
	EmailConsent   bool          `json:"email_consent"`
	EventRole      EventRoleType `json:"event_role"`
}

func (q *Queries) GetUsesWithRoles(ctx context.Context) ([]GetUsesWithRolesRow, error) {
	rows, err := q.db.Query(ctx, getUsesWithRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsesWithRolesRow{}
	for rows.Next() {
		var i GetUsesWithRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Onboarded,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.PreferredEmail,
			&i.EmailConsent,
			&i.EventRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRole = `-- name: RemoveRole :exec
DELETE FROM event_roles
WHERE user_id = $1
`

func (q *Queries) RemoveRole(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeRole, userID)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE event_roles
SET role = $2
WHERE user_id = $1
`

type UpdateRoleParams struct {
	UserID uuid.UUID     `json:"user_id"`
	Role   EventRoleType `json:"role"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.UserID, arg.Role)
	return err
}

const updateRoleByUserId = `-- name: UpdateRoleByUserId :exec
UPDATE event_roles
SET
  role = CASE WHEN $1::boolean THEN $2 ELSE role END,
  rfid = CASE WHEN $3::boolean THEN $4 ELSE rfid END,
  checked_in_at = CASE WHEN $5::boolean THEN $6 ELSE checked_in_at END
WHERE user_id = $7
`

type UpdateRoleByUserIdParams struct {
	RoleDoUpdate        bool          `json:"role_do_update"`
	Role                EventRoleType `json:"role"`
	RfidDoUpdate        bool          `json:"rfid_do_update"`
	Rfid                *string       `json:"rfid"`
	CheckedInAtDoUpdate bool          `json:"checked_in_at_do_update"`
	CheckedInAt         *time.Time    `json:"checked_in_at"`
	UserID              uuid.UUID     `json:"user_id"`
}

func (q *Queries) UpdateRoleByUserId(ctx context.Context, arg UpdateRoleByUserIdParams) error {
	_, err := q.db.Exec(ctx, updateRoleByUserId,
		arg.RoleDoUpdate,
		arg.Role,
		arg.RfidDoUpdate,
		arg.Rfid,
		arg.CheckedInAtDoUpdate,
		arg.CheckedInAt,
		arg.UserID,
	)
	return err
}
