// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interest_submissions.sql

package sqlc

import (
	"context"
)

const addEmail = `-- name: AddEmail :one
INSERT INTO interest_submissions (
    email,
    source
) VALUES (
    $1, $2
)
RETURNING id, email, created_at, source, hackathon_id
`

type AddEmailParams struct {
	Email  string  `json:"email"`
	Source *string `json:"source"`
}

// Adds a new email to the mailing list for a specific user.
// The unique constraint on `email` will prevent duplicates.
// Returns the newly created email record.
func (q *Queries) AddEmail(ctx context.Context, arg AddEmailParams) (InterestSubmission, error) {
	row := q.db.QueryRow(ctx, addEmail, arg.Email, arg.Source)
	var i InterestSubmission
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.Source,
		&i.HackathonID,
	)
	return i, err
}
