// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ApplicationStatus string

const (
	ApplicationStatusStarted     ApplicationStatus = "started"
	ApplicationStatusSubmitted   ApplicationStatus = "submitted"
	ApplicationStatusUnderReview ApplicationStatus = "under_review"
	ApplicationStatusAccepted    ApplicationStatus = "accepted"
	ApplicationStatusRejected    ApplicationStatus = "rejected"
	ApplicationStatusWaitlisted  ApplicationStatus = "waitlisted"
	ApplicationStatusWithdrawn   ApplicationStatus = "withdrawn"
)

func (e *ApplicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplicationStatus(s)
	case string:
		*e = ApplicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplicationStatus: %T", src)
	}
	return nil
}

type NullApplicationStatus struct {
	ApplicationStatus ApplicationStatus `json:"application_status"`
	Valid             bool              `json:"valid"` // Valid is true if ApplicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApplicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplicationStatus), nil
}

type BatRunStatus string

const (
	BatRunStatusRunning   BatRunStatus = "running"
	BatRunStatusCompleted BatRunStatus = "completed"
	BatRunStatusFailed    BatRunStatus = "failed"
)

func (e *BatRunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BatRunStatus(s)
	case string:
		*e = BatRunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BatRunStatus: %T", src)
	}
	return nil
}

type NullBatRunStatus struct {
	BatRunStatus BatRunStatus `json:"bat_run_status"`
	Valid        bool         `json:"valid"` // Valid is true if BatRunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBatRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BatRunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BatRunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBatRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BatRunStatus), nil
}

type TeamInvitationStatus string

const (
	TeamInvitationStatusPending  TeamInvitationStatus = "pending"
	TeamInvitationStatusAccepted TeamInvitationStatus = "accepted"
	TeamInvitationStatusExpired  TeamInvitationStatus = "expired"
	TeamInvitationStatusRejected TeamInvitationStatus = "rejected"
)

func (e *TeamInvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamInvitationStatus(s)
	case string:
		*e = TeamInvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamInvitationStatus: %T", src)
	}
	return nil
}

type NullTeamInvitationStatus struct {
	TeamInvitationStatus TeamInvitationStatus `json:"team_invitation_status"`
	Valid                bool                 `json:"valid"` // Valid is true if TeamInvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TeamInvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamInvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamInvitationStatus), nil
}

type TeamJoinRequestStatus string

const (
	TeamJoinRequestStatusPending  TeamJoinRequestStatus = "pending"
	TeamJoinRequestStatusApproved TeamJoinRequestStatus = "approved"
	TeamJoinRequestStatusRejected TeamJoinRequestStatus = "rejected"
)

func (e *TeamJoinRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamJoinRequestStatus(s)
	case string:
		*e = TeamJoinRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamJoinRequestStatus: %T", src)
	}
	return nil
}

type NullTeamJoinRequestStatus struct {
	TeamJoinRequestStatus TeamJoinRequestStatus `json:"team_join_request_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if TeamJoinRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamJoinRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TeamJoinRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamJoinRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamJoinRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamJoinRequestStatus), nil
}

type UserRole string

const (
	UserRoleAdmin     UserRole = "admin"
	UserRoleStaff     UserRole = "staff"
	UserRoleAttendee  UserRole = "attendee"
	UserRoleApplicant UserRole = "applicant"
	UserRoleVisitor   UserRole = "visitor"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Account struct {
	ID                    uuid.UUID  `json:"id"`
	UserID                uuid.UUID  `json:"user_id"`
	ProviderID            string     `json:"provider_id"`
	AccountID             string     `json:"account_id"`
	HashedPassword        *string    `json:"hashed_password"`
	AccessToken           *string    `json:"access_token"`
	RefreshToken          *string    `json:"refresh_token"`
	IDToken               *string    `json:"id_token"`
	AccessTokenExpiresAt  *time.Time `json:"access_token_expires_at"`
	RefreshTokenExpiresAt *time.Time `json:"refresh_token_expires_at"`
	Scope                 *string    `json:"scope"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
}

type Application struct {
	UserID             uuid.UUID         `json:"user_id"`
	Status             ApplicationStatus `json:"status"`
	Application        []byte            `json:"application"`
	CreatedAt          time.Time         `json:"created_at"`
	SavedAt            time.Time         `json:"saved_at"`
	UpdatedAt          time.Time         `json:"updated_at"`
	SubmittedAt        *time.Time        `json:"submitted_at"`
	ExperienceRating   *int32            `json:"experience_rating"`
	PassionRating      *int32            `json:"passion_rating"`
	AssignedReviewerID *uuid.UUID        `json:"assigned_reviewer_id"`
	WaitlistJoinTime   *time.Time        `json:"waitlist_join_time"`
	HackathonID        string            `json:"hackathon_id"`
}

type BatRun struct {
	ID                 uuid.UUID    `json:"id"`
	AcceptedApplicants []uuid.UUID  `json:"accepted_applicants"`
	RejectedApplicants []uuid.UUID  `json:"rejected_applicants"`
	Status             BatRunStatus `json:"status"`
	CreatedAt          time.Time    `json:"created_at"`
	CompletedAt        *time.Time   `json:"completed_at"`
	HackathonID        string       `json:"hackathon_id"`
}

type Hackathon struct {
	ID                       string     `json:"id"`
	Name                     string     `json:"name"`
	Description              *string    `json:"description"`
	Location                 *string    `json:"location"`
	LocationUrl              *string    `json:"location_url"`
	MaxAttendees             *int32     `json:"max_attendees"`
	ApplicationOpen          time.Time  `json:"application_open"`
	ApplicationClose         time.Time  `json:"application_close"`
	RsvpDeadline             *time.Time `json:"rsvp_deadline"`
	DecisionRelease          *time.Time `json:"decision_release"`
	StartTime                time.Time  `json:"start_time"`
	EndTime                  time.Time  `json:"end_time"`
	WebsiteUrl               *string    `json:"website_url"`
	IsPublished              *bool      `json:"is_published"`
	CreatedAt                time.Time  `json:"created_at"`
	UpdatedAt                time.Time  `json:"updated_at"`
	Banner                   *string    `json:"banner"`
	ApplicationReviewStarted bool       `json:"application_review_started"`
	OnerowID                 bool       `json:"onerow_id"`
}

type InterestSubmission struct {
	ID          uuid.UUID `json:"id"`
	Email       string    `json:"email"`
	CreatedAt   time.Time `json:"created_at"`
	Source      *string   `json:"source"`
	HackathonID string    `json:"hackathon_id"`
}

type Redeemable struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Amount        int32     `json:"amount"`
	MaxUserAmount int32     `json:"max_user_amount"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	HackathonID   string    `json:"hackathon_id"`
}

type Session struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	ExpiresAt  time.Time `json:"expires_at"`
	IpAddress  *string   `json:"ip_address"`
	UserAgent  *string   `json:"user_agent"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	LastUsedAt time.Time `json:"last_used_at"`
}

type Team struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	OwnerID     *uuid.UUID `json:"owner_id"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	HackathonID string     `json:"hackathon_id"`
}

type TeamInvitation struct {
	ID              uuid.UUID            `json:"id"`
	TeamID          uuid.UUID            `json:"team_id"`
	InvitedByUserID uuid.UUID            `json:"invited_by_user_id"`
	InvitedEmail    string               `json:"invited_email"`
	InvitedUserID   *uuid.UUID           `json:"invited_user_id"`
	Status          TeamInvitationStatus `json:"status"`
	ExpiresAt       *time.Time           `json:"expires_at"`
	CreatedAt       time.Time            `json:"created_at"`
	UpdatedAt       time.Time            `json:"updated_at"`
}

type TeamJoinRequest struct {
	ID                uuid.UUID             `json:"id"`
	TeamID            uuid.UUID             `json:"team_id"`
	UserID            uuid.UUID             `json:"user_id"`
	RequestMessage    *string               `json:"request_message"`
	Status            TeamJoinRequestStatus `json:"status"`
	ProcessedByUserID *uuid.UUID            `json:"processed_by_user_id"`
	ProcessedAt       *time.Time            `json:"processed_at"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
}

type TeamMember struct {
	UserID      uuid.UUID `json:"user_id"`
	TeamID      uuid.UUID `json:"team_id"`
	JoinedAt    time.Time `json:"joined_at"`
	HackathonID string    `json:"hackathon_id"`
}

type User struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	Email          *string    `json:"email"`
	EmailVerified  bool       `json:"email_verified"`
	Onboarded      bool       `json:"onboarded"`
	Image          *string    `json:"image"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	PreferredEmail *string    `json:"preferred_email"`
	EmailConsent   bool       `json:"email_consent"`
	CheckedInAt    *time.Time `json:"checked_in_at"`
	Rfid           *string    `json:"rfid"`
	RoleAssignedAt *time.Time `json:"role_assigned_at"`
	Role           UserRole   `json:"role"`
}

type UserRedemption struct {
	UserID       uuid.UUID `json:"user_id"`
	RedeemableID uuid.UUID `json:"redeemable_id"`
	Amount       int32     `json:"amount"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	HackathonID  string    `json:"hackathon_id"`
}
